# Generated by Django 5.1.7 on 2026-05-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_postbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreport",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commentreport",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postreport",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postreport",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
