# Generated by Django 5.1 on 2025-02-07 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('regular', 'Regular User'), ('tattoo_artist', 'Tattoo Artist')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('active', 'Активный')], default='pending', max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('verification_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_type', models.CharField(choices=[('passport', 'Паспорт'), ('driver_license', 'Водительское удостоверение'), ('national_id', 'Национальное удостоверение личности')], max_length=50, verbose_name='Тип документа личности')),
                ('id_document_file', models.FileField(upload_to='id_docs/', verbose_name='Документ удостоверяющий личность')),
                ('business_document_type', models.CharField(choices=[('kbis', 'Регистрация бизнеса'), ('sole_proprietor', 'Свидетельство самозанятого'), ('business_license', 'Лицензия на тату-салон'), ('other', 'Другой (Загрузите официальный документ)')], max_length=50, verbose_name='Тип документа бизнеса')),
                ('business_document_file', models.FileField(upload_to='business_docs/', verbose_name='Документ о бизнесе')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Документ проверен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
