# Generated by Django 5.1 on 2025-02-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='business_document_type',
            field=models.CharField(choices=[('license', 'Лицензия на деятельность'), ('sole_proprietor', 'Свидетельство самозанятого'), ('business_registration', 'Регистрация тату-салона'), ('other', 'Другой (Загрузите официальный документ)')], max_length=50, verbose_name='Тип бизнес-документа'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
