# Generated by Django 5.1.7 on 2026-03-05 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="business_document_type",
            field=models.CharField(
                choices=[
                    ("license", "Лицензия на деятельность"),
                    ("sole_proprietor", "Свидетельство самозанятого"),
                    ("business_registration", "Регистрация тату-салона"),
                    ("other", "Другой (Загрузите официальный документ)"),
                ],
                max_length=50,
                verbose_name="Тип бизнес-документа",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
