# Generated by Django 5.1.7 on 2026-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_liked_posts",
            field=models.BooleanField(default=True),
        ),
    ]
