# Generated by Django 5.1.7 on 2026-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_show_liked_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tag",
            field=models.SlugField(
                blank=True,
                help_text="Unique public tag used to find the profile.",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
    ]
