# Generated by Django 5.1.7 on 2026-05-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not submitted"),
                    ("pending_documents", "Pending documents review"),
                    ("pending_manual_review", "Pending manual review"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_submitted",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ManualVerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portfolio_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Portfolio link",
                    ),
                ),
                (
                    "social_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Social media link",
                    ),
                ),
                (
                    "city_country",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="City / Country",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Explain why you should be reviewed manually.",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "extra_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="manual_review_files/",
                        verbose_name="Optional file",
                    ),
                ),
                ("is_reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
