# Generated by Django 5.1.7 on 2026-03-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_disable_comments_post_is_ad_post_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='order',
        ),
    ]
