# Generated by Django 5.1 on 2024-09-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_verified_verificationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_documents/'),
        ),
    ]
