# Generated by Django 5.1.7 on 2026-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_postmedia_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='post',
            name='layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('carousel', 'Carousel')], default='grid', max_length=10),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
