# Generated by Django 5.1 on 2024-09-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verificationdocument_identity_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('certificate', 'Certificate of Qualification'), ('license', 'License'), ('registration', 'Registration Document')], max_length=20),
        ),
    ]
