# Generated by Django 5.1.7 on 2026-05-25 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_chatthread_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="chat_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="users.chatmessage",
                    ),
                ),
            ],
        ),
    ]
