# Generated by Django 5.1 on 2024-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_verificationdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_notification',
            field=models.CharField(blank=True, choices=[('approved', 'Congratulations, your tattoo artist account has been verified..'), ('rejected', 'Unfortunately, your tattoo artist account has not been verified. Contact tech. support for more information.')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
