# Generated by Django 5.1 on 2024-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_last_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_notification',
            field=models.CharField(blank=True, choices=[('approved', 'Congratulations, your tattoo artist account has been verified..'), ('rejected', 'Unfortunately, your tattoo artist account has not been verified. Contact tech. support for more information.')], max_length=20, null=True),
        ),
    ]
