# Generated by Django 5.1 on 2024-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_last_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_notification',
            field=models.CharField(blank=True, choices=[('approved', 'Congratulations, your tattoo artist account has been verified.'), ('rejected', 'Unfortunately, your tattoo artist account has not been verified. Contact tech. support for more information.')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
