# Generated by Django 5.1.7 on 2026-06-03 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_userreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userreport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User report",
                "verbose_name_plural": "User reports",
            },
        ),
        migrations.AlterField(
            model_name="userreport",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="reports/", verbose_name="Attachment"
            ),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="is_resolved",
            field=models.BooleanField(default=False, verbose_name="Resolved"),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="page_url",
            field=models.CharField(blank=True, max_length=500, verbose_name="Page URL"),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("bug", "Bug"),
                    ("suggestion", "Suggestion"),
                    ("other", "Other"),
                ],
                default="bug",
                max_length=20,
                verbose_name="Report type",
            ),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="title",
            field=models.CharField(max_length=120, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
