# Generated by Django 5.1.7 on 2026-06-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_userreport_options_alter_userreport_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular user"),
                    ("tattoo_artist", "Tattoo artist"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("active", "Active")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="business_document_file",
            field=models.FileField(
                upload_to="business_docs", verbose_name="Business document"
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="business_document_type",
            field=models.CharField(
                choices=[
                    ("license", "Business license"),
                    ("sole_proprietor", "Self-employed certificate"),
                    ("business_registration", "Tattoo studio registration"),
                    ("other", "Other (upload an official document)"),
                ],
                max_length=50,
                verbose_name="Business document type",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="id_document_file",
            field=models.FileField(
                upload_to="id_docs", verbose_name="Identity document"
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="id_document_type",
            field=models.CharField(
                choices=[
                    ("passport", "Passport"),
                    ("driver_license", "Driver license"),
                    ("national_id", "National ID"),
                ],
                max_length=50,
                verbose_name="Identity document type",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Document verified"),
        ),
    ]
