# Generated by Django 5.1.7 on 2026-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_reset_prod_superuser_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatattachment",
            name="content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="original_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
