# Generated by Django 5.1.7 on 2026-06-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_chatattachment_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatattachment",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="chatattachment",
            name="original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
