# Generated by Django 5.1.7 on 2026-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_chatattachment_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatattachment",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video"), ("file", "File")],
                default="file",
                max_length=20,
            ),
        ),
    ]
