# Generated by Django 5.1.7 on 2026-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_add_chat_attachment_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
