# Generated by Django 5.1.7 on 2026-06-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_chat_message_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
