# Generated by Django 5.1.7 on 2026-07-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_location_locationclaim_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=120)),
                ("address_or_link", models.TextField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="users_locat_status_1c9ba3_idx",
                    ),
                    models.Index(
                        fields=["city", "country"], name="users_locat_city_189dd0_idx"
                    ),
                    models.Index(
                        fields=["contact_email", "status"],
                        name="users_locat_contact_77e760_idx",
                    ),
                ],
            },
        ),
    ]
