# Generated by Django 5.1.7 on 2026-07-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_locationrequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locationrequest",
            old_name="address_or_link",
            new_name="full_address",
        ),
        migrations.AddField(
            model_name="locationrequest",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="locationrequest",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="locationrequest",
            name="phone",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="locationrequest",
            name="website_or_map_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
