# Generated by Django 5.1.7 on 2026-07-08 22:25

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_rename_address_or_link_locationrequest_full_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationclaim",
            name="proof_document",
            field=models.FileField(
                blank=True,
                upload_to="location_claim_proofs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "webp"]
                    ),
                    users.models.validate_location_upload_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="locationrequest",
            name="supporting_file",
            field=models.FileField(
                blank=True,
                upload_to="location_request_supporting_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "webp"]
                    ),
                    users.models.validate_location_upload_size,
                ],
            ),
        ),
    ]
