# Generated by Django 5.1.7 on 2026-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_private_media_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Europe/Paris', help_text='Time zone used for bookings and calendar times.', max_length=64),
        ),
    ]
