import { ApiError } from '@/api/client';
import type { AppLanguage } from '@/localization/language-context';


const copy = {
  en: {
    welcome: 'Welcome',
    signIn: 'Log in',
    signUp: 'Sign up',
    createAccount: 'Create account',
    username: 'Username',
    identifierPlaceholder: 'Username or email',
    usernamePlaceholder: 'Choose a username',
    email: 'Email',
    emailPlaceholder: 'Enter your email',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: 'Repeat your password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    noAccount: 'New to Tatzo?',
    hasAccount: 'Already have an account?',
    forgotPassword: 'Forgot password?',
    regularTitle: 'Regular user',
    regularBody: 'Discover inspiration and book sessions with tattoo artists.',
    artistTitle: 'Tattoo artist',
    artistBody: 'Publish your work and attract new clients.',
    regularInfo: 'Join our community and discover the world of tattoo!',
    artistInfo: 'Join our community! Tattoo artists can verify their status after registration.',
    usernameHint: 'Your unique @tag is created automatically from your username. You can change it later in profile settings.',
    passwordHint: 'Use at least 8 characters, one uppercase letter and one number.',
    acceptPrefix: 'I accept the',
    terms: 'Terms',
    privacy: 'Privacy Policy',
    communityGuidelines: 'Community Guidelines',
    and: 'and',
    verifyTitle: 'Check your email',
    verifyBody: 'We sent a confirmation link to',
    verifyHint: 'Confirm your account from the email, then come back and log in.',
    backToLogin: 'Back to log in',
    passwordsMismatch: 'The passwords do not match.',
    acceptRequired: 'Accept the Terms, Privacy Policy and Community Guidelines to continue.',
    invalidCredentials: 'The username/email or password is incorrect.',
    emailNotVerified: 'Confirm your email before logging in.',
    rateLimited: 'Too many attempts. Please wait a little and try again.',
    genericError: 'Something went wrong. Please try again.',
  },
  fr: {
    welcome: 'Bienvenue',
    signIn: 'Se connecter',
    signUp: "S'inscrire",
    createAccount: 'Créer un compte',
    username: "Nom d'utilisateur",
    identifierPlaceholder: "Nom d'utilisateur ou e-mail",
    usernamePlaceholder: "Choisissez un nom d'utilisateur",
    email: 'E-mail',
    emailPlaceholder: 'Saisissez votre e-mail',
    password: 'Mot de passe',
    passwordPlaceholder: 'Saisissez votre mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    confirmPasswordPlaceholder: 'Répétez votre mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    noAccount: 'Nouveau sur Tatzo ?',
    hasAccount: 'Vous avez déjà un compte ?',
    forgotPassword: 'Mot de passe oublié ?',
    regularTitle: 'Utilisateur',
    regularBody: "Découvrez des inspirations et réservez des séances avec des tatoueurs.",
    artistTitle: 'Tatoueur',
    artistBody: 'Publiez votre travail et attirez de nouveaux clients.',
    regularInfo: 'Rejoignez notre communauté et découvrez le monde du tatouage !',
    artistInfo: 'Rejoignez notre communauté ! Les tatoueurs pourront vérifier leur statut après inscription.',
    usernameHint: "Votre @tag unique est créé automatiquement à partir de votre nom d'utilisateur. Vous pourrez le modifier plus tard dans votre profil.",
    passwordHint: 'Utilisez au moins 8 caractères, une majuscule et un chiffre.',
    acceptPrefix: "J'accepte les",
    terms: "Conditions d'utilisation",
    privacy: 'Politique de confidentialité',
    communityGuidelines: 'Règles de la communauté',
    and: 'et les',
    verifyTitle: 'Consultez votre e-mail',
    verifyBody: 'Nous avons envoyé un lien de confirmation à',
    verifyHint: 'Confirmez votre compte depuis cet e-mail, puis revenez vous connecter.',
    backToLogin: 'Retour à la connexion',
    passwordsMismatch: 'Les mots de passe ne correspondent pas.',
    acceptRequired: "Acceptez les conditions, la politique de confidentialité et les règles de la communauté pour continuer.",
    invalidCredentials: "Le nom d'utilisateur/e-mail ou le mot de passe est incorrect.",
    emailNotVerified: 'Confirmez votre e-mail avant de vous connecter.',
    rateLimited: 'Trop de tentatives. Patientez un peu puis réessayez.',
    genericError: 'Une erreur est survenue. Réessayez.',
  },
  ru: {
    welcome: 'Добро пожаловать',
    signIn: 'Войти',
    signUp: 'Зарегистрироваться',
    createAccount: 'Создать аккаунт',
    username: 'Имя пользователя',
    identifierPlaceholder: 'Имя пользователя или email',
    usernamePlaceholder: 'Выберите имя пользователя',
    email: 'Email',
    emailPlaceholder: 'Введите email',
    password: 'Пароль',
    passwordPlaceholder: 'Введите пароль',
    confirmPassword: 'Повторите пароль',
    confirmPasswordPlaceholder: 'Повторите пароль',
    showPassword: 'Показать пароль',
    hidePassword: 'Скрыть пароль',
    noAccount: 'Впервые в Tatzo?',
    hasAccount: 'Уже есть аккаунт?',
    forgotPassword: 'Забыли пароль?',
    regularTitle: 'Любитель татуировок',
    regularBody: 'Ищите вдохновение и записывайтесь к тату-мастерам.',
    artistTitle: 'Тату-мастер',
    artistBody: 'Публикуйте работы и находите новых клиентов.',
    regularInfo: 'Присоединяйтесь к сообществу и открывайте мир татуировок!',
    artistInfo: 'Присоединяйтесь к сообществу! После регистрации тату-мастер сможет подтвердить свой статус.',
    usernameHint: 'Уникальный @тег создаётся автоматически из имени пользователя. Позже его можно изменить в профиле.',
    passwordHint: 'Минимум 8 символов, одна заглавная буква и одна цифра.',
    acceptPrefix: 'Я принимаю',
    terms: 'Условия использования',
    privacy: 'Политику конфиденциальности',
    communityGuidelines: 'Правила сообщества',
    and: 'и',
    verifyTitle: 'Проверьте почту',
    verifyBody: 'Мы отправили ссылку для подтверждения на',
    verifyHint: 'Подтвердите аккаунт по ссылке в письме, затем вернитесь и войдите.',
    backToLogin: 'Вернуться ко входу',
    passwordsMismatch: 'Пароли не совпадают.',
    acceptRequired: 'Примите Условия, Политику конфиденциальности и Правила сообщества, чтобы продолжить.',
    invalidCredentials: 'Неверное имя пользователя/email или пароль.',
    emailNotVerified: 'Подтвердите email перед входом.',
    rateLimited: 'Слишком много попыток. Немного подождите и попробуйте снова.',
    genericError: 'Что-то пошло не так. Попробуйте ещё раз.',
  },
} as const;

export type AuthCopy = (typeof copy)['en'];

export function authCopy(language: AppLanguage): AuthCopy {
  return copy[language] as AuthCopy;
}

export function authError(error: unknown, language: AppLanguage): string {
  const text = authCopy(language);
  if (!(error instanceof ApiError)) return text.genericError;
  if (error.body.code === 'invalid_credentials') return text.invalidCredentials;
  if (error.body.code === 'email_not_verified') return text.emailNotVerified;
  if (error.body.code === 'rate_limited') return text.rateLimited;

  const fieldError = Object.values(error.body).find(Array.isArray);
  if (Array.isArray(fieldError) && typeof fieldError[0] === 'string') {
    return fieldError[0];
  }
  return typeof error.body.detail === 'string' ? error.body.detail : text.genericError;
}
