COPY = {
    "en": {
        "dashboard_title": "Stripe payouts",
        "dashboard_intro": "Connect Stripe before requiring deposits. Tatzo currently takes 0% commission; Stripe processing fees are charged to your Stripe account.",
        "not_connected": "Stripe is not connected",
        "onboarding": "Finish Stripe onboarding",
        "ready": "Ready to accept deposits",
        "connect": "Connect Stripe",
        "continue": "Continue Stripe setup",
        "payments_unavailable": "Stripe payments are not configured on Tatzo yet.",
        "deposit_notice_title": "Deposit",
        "deposit_notice": "This artist requires a €%(amount)s deposit after accepting your booking. You are not charged when you send this request.",
        "deposit_title": "Booking deposit",
        "deposit_pending": "A €%(amount)s deposit is required to secure this accepted appointment.",
        "deposit_checkout": "Pay €%(amount)s deposit",
        "deposit_paid": "Deposit paid",
        "deposit_refunded": "Deposit refunded",
        "deposit_expired": "Deposit payment window expired",
        "deposit_cancelled": "Deposit cancelled",
        "deposit_failed": "The last payment attempt failed. You can try again.",
        "deposit_artist_pending": "Waiting for the client to pay the €%(amount)s deposit.",
        "deposit_artist_paid": "The €%(amount)s deposit has been paid.",
        "deposit_due": "Payment deadline",
        "payment_return": "Stripe returned you to Tatzo. Payment status is confirmed by Stripe and may take a moment to update.",
        "connect_error": "Stripe setup could not be started. Please try again.",
        "checkout_error": "The Stripe checkout could not be created. Please try again.",
        "deposit_settings_title": "Booking deposits",
        "deposit_settings_intro": "After Stripe is ready, you can require a fixed deposit when accepting tattoo bookings.",
        "deposit_toggle": "Require a deposit for accepted tattoo bookings",
        "deposit_amount_label": "Deposit amount in EUR",
        "save_settings": "Save deposit settings",
        "settings_saved": "Deposit settings saved.",
    },
    "fr": {
        "dashboard_title": "Paiements Stripe",
        "dashboard_intro": "Connectez Stripe avant d'exiger un acompte. Tatzo prélève actuellement 0 % de commission ; les frais de traitement Stripe sont facturés à votre compte Stripe.",
        "not_connected": "Stripe n'est pas connecté",
        "onboarding": "Terminer la configuration Stripe",
        "ready": "Prêt à accepter des acomptes",
        "connect": "Connecter Stripe",
        "continue": "Continuer la configuration Stripe",
        "payments_unavailable": "Les paiements Stripe ne sont pas encore configurés sur Tatzo.",
        "deposit_notice_title": "Acompte",
        "deposit_notice": "Ce tatoueur demande un acompte de %(amount)s € après acceptation de la réservation. Aucun montant n'est débité lors de l'envoi de la demande.",
        "deposit_title": "Acompte de réservation",
        "deposit_pending": "Un acompte de %(amount)s € est nécessaire pour sécuriser ce rendez-vous accepté.",
        "deposit_checkout": "Payer l'acompte de %(amount)s €",
        "deposit_paid": "Acompte payé",
        "deposit_refunded": "Acompte remboursé",
        "deposit_expired": "Le délai de paiement de l'acompte est expiré",
        "deposit_cancelled": "Acompte annulé",
        "deposit_failed": "La dernière tentative de paiement a échoué. Vous pouvez réessayer.",
        "deposit_artist_pending": "En attente du paiement de l'acompte de %(amount)s € par le client.",
        "deposit_artist_paid": "L'acompte de %(amount)s € a été payé.",
        "deposit_due": "Date limite de paiement",
        "payment_return": "Stripe vous a redirigé vers Tatzo. Le statut est confirmé par Stripe et peut prendre quelques instants à se mettre à jour.",
        "connect_error": "Impossible de démarrer la configuration Stripe. Réessayez.",
        "checkout_error": "Impossible de créer le paiement Stripe. Réessayez.",
        "deposit_settings_title": "Acomptes de réservation",
        "deposit_settings_intro": "Une fois Stripe prêt, vous pouvez exiger un acompte fixe lors de l’acceptation d’une réservation de tatouage.",
        "deposit_toggle": "Exiger un acompte pour les réservations de tatouage acceptées",
        "deposit_amount_label": "Montant de l’acompte en EUR",
        "save_settings": "Enregistrer les paramètres d’acompte",
        "settings_saved": "Paramètres d’acompte enregistrés.",
    },
    "ru": {
        "dashboard_title": "Выплаты через Stripe",
        "dashboard_intro": "Подключите Stripe перед включением предоплаты. Сейчас Tatzo берёт 0% комиссии; комиссия за обработку платежа списывается Stripe с аккаунта мастера.",
        "not_connected": "Stripe не подключён",
        "onboarding": "Завершите настройку Stripe",
        "ready": "Можно принимать предоплату",
        "connect": "Подключить Stripe",
        "continue": "Продолжить настройку Stripe",
        "payments_unavailable": "Платежи Stripe пока не настроены на Tatzo.",
        "deposit_notice_title": "Предоплата",
        "deposit_notice": "Этот мастер требует предоплату %(amount)s € после принятия записи. При отправке заявки деньги не списываются.",
        "deposit_title": "Предоплата за запись",
        "deposit_pending": "Для закрепления принятой записи требуется предоплата %(amount)s €.",
        "deposit_checkout": "Оплатить %(amount)s €",
        "deposit_paid": "Предоплата оплачена",
        "deposit_refunded": "Предоплата возвращена",
        "deposit_expired": "Срок оплаты предоплаты истёк",
        "deposit_cancelled": "Предоплата отменена",
        "deposit_failed": "Последняя попытка оплаты не прошла. Можно попробовать ещё раз.",
        "deposit_artist_pending": "Ожидается предоплата %(amount)s € от клиента.",
        "deposit_artist_paid": "Предоплата %(amount)s € получена.",
        "deposit_due": "Оплатить до",
        "payment_return": "Stripe вернул вас в Tatzo. Статус подтверждается webhook от Stripe и может обновиться через несколько секунд.",
        "connect_error": "Не удалось начать настройку Stripe. Попробуйте ещё раз.",
        "checkout_error": "Не удалось создать оплату Stripe. Попробуйте ещё раз.",
        "deposit_settings_title": "Предоплата за записи",
        "deposit_settings_intro": "После настройки Stripe можно требовать фиксированную предоплату при принятии заявки на тату-сеанс.",
        "deposit_toggle": "Требовать предоплату для принятых записей на тату-сеанс",
        "deposit_amount_label": "Сумма предоплаты в EUR",
        "save_settings": "Сохранить настройки предоплаты",
        "settings_saved": "Настройки предоплаты сохранены.",
    },
}


def get_copy(request):
    language = (getattr(request, "LANGUAGE_CODE", "en") or "en").split("-")[0]
    return COPY.get(language, COPY["en"])
