COPY = {
    "en": {
        "nav": "Health & safety",
        "eyebrow": "PRIVATE HEALTH & SAFETY",
        "title": "Share only what matters for a safer tattoo session.",
        "intro": "This private card helps you tell a tattoo artist about health information that may be relevant to bleeding, skin reactions or healing. Tatzo does not diagnose conditions or replace medical advice.",
        "privacy": "Your card is private by default. An artist sees it only when you explicitly share it for a specific tattoo appointment. You can revoke access later.",
        "bleeding": "Bleeding or clotting condition",
        "blood_thinners": "Medication or treatment that can affect bleeding",
        "diabetes": "Diabetes or another blood-sugar condition",
        "skin": "Skin condition relevant to tattooing or the tattoo area",
        "allergy": "Allergy or sensitivity relevant to tattoo products",
        "immune": "Condition or treatment that may affect healing or immunity",
        "other": "Other health information relevant to tattoo safety",
        "other_help": "Keep this limited to information the artist needs for tattoo safety. Do not upload medical records or test results.",
        "consent": "I explicitly agree that Tatzo stores the health information I enter here for tattoo safety and booking support. I understand that I can delete this card at any time.",
        "save": "Save private card",
        "delete": "Delete health card",
        "saved": "Your private Health & Safety Card was saved.",
        "deleted": "Your Health & Safety Card was deleted.",
        "consent_required": "Please confirm the health-data consent before saving.",
        "shared_with": "Shared appointments",
        "no_shares": "You are not currently sharing this card with any tattoo appointment.",
        "revoke": "Revoke artist access",
        "booking_title": "Health & Safety",
        "booking_ready": "Choose how you want to handle health information for this tattoo appointment.",
        "booking_share": "Share my saved Health & Safety Card with this artist for this tattoo appointment",
        "booking_missing": "You do not have a saved Health & Safety Card. You can answer a few optional safety questions here without creating one.",
        "booking_create": "Open my private Health & Safety Card",
        "booking_quick": "Answer here for this appointment only",
        "booking_quick_intro": "Only the answers below are shared with this artist for this appointment. They are not added to your permanent card unless you choose to save them.",
        "booking_none": "Do not share health information for this appointment",
        "booking_confirm_none": "As far as I know, none of the listed health or skin issues apply to me",
        "booking_quick_consent": "I explicitly agree to share these health answers with this artist for this tattoo appointment.",
        "booking_save_quick": "Also save these answers to my private Health & Safety Card for future bookings. I explicitly agree that Tatzo stores them until I update or delete that card.",
        "booking_validation": "Select at least one relevant item, add a short note, or confirm that none of the listed items apply.",
        "booking_consent_required": "Please confirm that you agree to share these health answers with the artist.",
        "booking_error": "Tatzo could not confirm your health-information sharing choice. Please try again before sending the booking.",
        "artist_title": "Client Health & Safety",
        "artist_intro": "The client explicitly shared this private information for this tattoo appointment. Use it only to discuss tattoo safety; Tatzo does not provide a medical diagnosis.",
        "client_shared": "Your saved Health & Safety Card is shared with this artist for this appointment.",
        "client_quick_shared": "Your one-time Health & Safety declaration is shared with this artist for this appointment.",
        "client_not_shared": "No Health & Safety information is currently shared with this artist.",
        "share_now": "Share saved card with artist",
        "manage_card": "Manage private card",
        "expires": "Artist access ends after",
        "share_success": "Health & Safety access was shared with the artist.",
        "revoke_success": "Artist access to your Health & Safety information was revoked.",
        "none_declared": "No relevant items are currently declared.",
    },
    "fr": {
        "nav": "Santé et sécurité",
        "eyebrow": "SANTÉ & SÉCURITÉ PRIVÉES",
        "title": "Partagez uniquement ce qui peut aider à rendre la séance plus sûre.",
        "intro": "Cette fiche privée permet d'indiquer au tatoueur les informations de santé pouvant être pertinentes pour le saignement, les réactions cutanées ou la cicatrisation. Tatzo ne pose aucun diagnostic et ne remplace pas un avis médical.",
        "privacy": "Votre fiche est privée par défaut. Un tatoueur ne la voit que si vous la partagez explicitement pour un rendez-vous de tatouage précis. Vous pouvez retirer l'accès ensuite.",
        "bleeding": "Trouble de saignement ou de coagulation",
        "blood_thinners": "Médicament ou traitement pouvant affecter le saignement",
        "diabetes": "Diabète ou autre trouble de la glycémie",
        "skin": "Affection cutanée pertinente pour le tatouage ou la zone tatouée",
        "allergy": "Allergie ou sensibilité pertinente aux produits de tatouage",
        "immune": "Affection ou traitement pouvant affecter la cicatrisation ou l'immunité",
        "other": "Autre information de santé pertinente pour la sécurité du tatouage",
        "other_help": "Limitez-vous aux informations utiles au tatoueur pour la sécurité. N'ajoutez pas de dossier médical ni de résultats d'examens.",
        "consent": "J'accepte explicitement que Tatzo conserve les informations de santé saisies ici pour la sécurité du tatouage et la gestion des rendez-vous. Je comprends que je peux supprimer cette fiche à tout moment.",
        "save": "Enregistrer la fiche privée",
        "delete": "Supprimer la fiche santé",
        "saved": "Votre fiche privée Santé & Sécurité a été enregistrée.",
        "deleted": "Votre fiche Santé & Sécurité a été supprimée.",
        "consent_required": "Veuillez confirmer le consentement concernant les données de santé avant d'enregistrer.",
        "shared_with": "Rendez-vous partagés",
        "no_shares": "Vous ne partagez actuellement cette fiche avec aucun rendez-vous de tatouage.",
        "revoke": "Retirer l'accès du tatoueur",
        "booking_title": "Santé & Sécurité",
        "booking_ready": "Choisissez comment gérer les informations de santé pour ce rendez-vous de tatouage.",
        "booking_share": "Partager ma fiche Santé & Sécurité enregistrée avec ce tatoueur pour ce rendez-vous",
        "booking_missing": "Vous n'avez pas de fiche Santé & Sécurité enregistrée. Vous pouvez répondre ici à quelques questions facultatives sans créer de fiche.",
        "booking_create": "Ouvrir ma fiche privée Santé & Sécurité",
        "booking_quick": "Répondre ici uniquement pour ce rendez-vous",
        "booking_quick_intro": "Seules les réponses ci-dessous sont partagées avec ce tatoueur pour ce rendez-vous. Elles ne sont pas ajoutées à votre fiche permanente sauf si vous choisissez de les enregistrer.",
        "booking_none": "Ne partager aucune information de santé pour ce rendez-vous",
        "booking_confirm_none": "À ma connaissance, aucun des problèmes de santé ou de peau listés ne me concerne",
        "booking_quick_consent": "J'accepte explicitement de partager ces réponses de santé avec ce tatoueur pour ce rendez-vous.",
        "booking_save_quick": "Enregistrer aussi ces réponses dans ma fiche privée Santé & Sécurité pour les futurs rendez-vous. J'accepte explicitement que Tatzo les conserve jusqu'à la modification ou suppression de la fiche.",
        "booking_validation": "Sélectionnez au moins un élément pertinent, ajoutez une courte note ou confirmez qu'aucun des éléments listés ne vous concerne.",
        "booking_consent_required": "Veuillez confirmer que vous acceptez de partager ces réponses de santé avec le tatoueur.",
        "booking_error": "Tatzo n'a pas pu confirmer votre choix de partage des informations de santé. Réessayez avant d'envoyer la réservation.",
        "artist_title": "Santé & Sécurité du client",
        "artist_intro": "Le client a explicitement partagé ces informations privées pour ce rendez-vous. Utilisez-les uniquement pour discuter de la sécurité du tatouage ; Tatzo ne fournit aucun diagnostic médical.",
        "client_shared": "Votre fiche Santé & Sécurité enregistrée est partagée avec ce tatoueur pour ce rendez-vous.",
        "client_quick_shared": "Votre déclaration Santé & Sécurité ponctuelle est partagée avec ce tatoueur pour ce rendez-vous.",
        "client_not_shared": "Aucune information Santé & Sécurité n'est actuellement partagée avec ce tatoueur.",
        "share_now": "Partager la fiche enregistrée",
        "manage_card": "Gérer la fiche privée",
        "expires": "L'accès du tatoueur prend fin après le",
        "share_success": "L'accès Santé & Sécurité a été partagé avec le tatoueur.",
        "revoke_success": "L'accès du tatoueur à vos informations Santé & Sécurité a été retiré.",
        "none_declared": "Aucun élément pertinent n'est actuellement déclaré.",
    },
    "ru": {
        "nav": "Здоровье и безопасность",
        "eyebrow": "ПРИВАТНО: ЗДОРОВЬЕ И БЕЗОПАСНОСТЬ",
        "title": "Укажите только то, что действительно важно для более безопасного сеанса.",
        "intro": "Эта приватная карточка помогает сообщить тату-мастеру сведения о здоровье, которые могут быть важны для кровотечения, реакции кожи или заживления. Tatzo не ставит диагнозы и не заменяет консультацию врача.",
        "privacy": "По умолчанию карточка видна только вам. Мастер получает доступ только если вы явно поделитесь ею для конкретной записи на тату-сеанс. Доступ можно отозвать позже.",
        "bleeding": "Нарушение кровотечения или свёртывания крови",
        "blood_thinners": "Лекарства или лечение, которые могут влиять на кровотечение",
        "diabetes": "Диабет или другое состояние, связанное с уровнем сахара в крови",
        "skin": "Кожное заболевание, важное для татуировки или выбранной зоны",
        "allergy": "Аллергия или чувствительность, важная для материалов татуировки",
        "immune": "Заболевание или лечение, которое может влиять на иммунитет или заживление",
        "other": "Другие сведения о здоровье, важные для безопасности татуировки",
        "other_help": "Указывайте только информацию, которая нужна мастеру для безопасности татуировки. Не загружайте медицинские карты, анализы или заключения.",
        "consent": "Я явно соглашаюсь на хранение Tatzo указанных здесь сведений о здоровье для безопасности татуировки и сопровождения бронирования. Я понимаю, что могу удалить эту карточку в любой момент.",
        "save": "Сохранить приватную карточку",
        "delete": "Удалить медкарту",
        "saved": "Приватная карточка «Здоровье и безопасность» сохранена.",
        "deleted": "Карточка «Здоровье и безопасность» удалена.",
        "consent_required": "Перед сохранением подтвердите согласие на хранение данных о здоровье.",
        "shared_with": "Записи с доступом",
        "no_shares": "Сейчас карточка не открыта ни для одного тату-сеанса.",
        "revoke": "Отозвать доступ мастера",
        "booking_title": "Здоровье и безопасность",
        "booking_ready": "Выберите, как передать сведения о здоровье для этой записи на тату-сеанс.",
        "booking_share": "Поделиться моей сохранённой карточкой «Здоровье и безопасность» с этим мастером для этой записи",
        "booking_missing": "У вас нет сохранённой карточки «Здоровье и безопасность». Можно ответить на несколько необязательных вопросов прямо здесь и не создавать карточку.",
        "booking_create": "Открыть мою приватную карточку",
        "booking_quick": "Ответить здесь только для этой записи",
        "booking_quick_intro": "Только ответы ниже будут переданы этому мастеру для этой записи. Они не попадут в постоянную карточку, если вы отдельно не выберете сохранение.",
        "booking_none": "Не передавать сведения о здоровье для этой записи",
        "booking_confirm_none": "Насколько мне известно, ни одна из перечисленных проблем со здоровьем или кожей ко мне не относится",
        "booking_quick_consent": "Я явно согласен передать эти сведения о здоровье этому мастеру для этой конкретной записи.",
        "booking_save_quick": "Также сохранить эти ответы в моей приватной карточке «Здоровье и безопасность» для будущих записей. Я явно согласен на их хранение Tatzo до изменения или удаления карточки.",
        "booking_validation": "Отметьте хотя бы один важный пункт, добавьте короткое пояснение либо подтвердите, что перечисленные пункты к вам не относятся.",
        "booking_consent_required": "Подтвердите, что вы согласны передать эти сведения о здоровье мастеру.",
        "booking_error": "Tatzo не удалось подтвердить выбор доступа к данным о здоровье. Попробуйте ещё раз перед отправкой бронирования.",
        "artist_title": "Здоровье и безопасность клиента",
        "artist_intro": "Клиент явно поделился этой приватной информацией для конкретной записи. Используйте её только для обсуждения безопасности татуировки; Tatzo не ставит медицинских диагнозов.",
        "client_shared": "Ваша сохранённая карточка «Здоровье и безопасность» открыта этому мастеру для этой записи.",
        "client_quick_shared": "Ваша одноразовая декларация «Здоровье и безопасность» открыта этому мастеру для этой записи.",
        "client_not_shared": "Для этой записи мастеру сейчас не переданы сведения «Здоровье и безопасность».",
        "share_now": "Поделиться сохранённой карточкой",
        "manage_card": "Управлять приватной карточкой",
        "expires": "Доступ мастера закончится после",
        "share_success": "Доступ к сведениям «Здоровье и безопасность» открыт мастеру.",
        "revoke_success": "Доступ мастера к сведениям «Здоровье и безопасность» отозван.",
        "none_declared": "Значимые пункты не отмечены.",
    },
}


def language_code(request):
    language = (getattr(request, "LANGUAGE_CODE", "en") or "en").split("-")[0]
    return language if language in COPY else "en"


def get_copy(request):
    return COPY[language_code(request)]
