COPY = {
    "en": {
        "nav": "Health & safety",
        "eyebrow": "PRIVATE HEALTH & SAFETY",
        "title": "Share only what matters for a safer tattoo session.",
        "intro": "This private card helps you tell a tattoo artist about health information that may be relevant to bleeding, skin reactions or healing. Tatzo does not diagnose conditions or replace medical advice.",
        "privacy": "Your card is private by default. An artist sees it only when you explicitly share it for a specific tattoo appointment. You can revoke access later.",
        "bleeding": "Bleeding or clotting condition",
        "blood_thinners": "Medication or treatment that can affect bleeding",
        "diabetes": "Diabetes or another blood-sugar condition",
        "skin": "Skin condition relevant to tattooing or the tattoo area",
        "allergy": "Allergy or sensitivity relevant to tattoo products",
        "immune": "Condition or treatment that may affect healing or immunity",
        "other": "Other health information relevant to tattoo safety",
        "other_help": "Keep this limited to information the artist needs for tattoo safety. Do not upload medical records or test results.",
        "consent": "I explicitly agree that Tatzo stores the health information I enter here for tattoo safety and booking support. I understand that I can delete this card at any time.",
        "save": "Save private card",
        "delete": "Delete health card",
        "saved": "Your private Health & Safety Card was saved.",
        "deleted": "Your Health & Safety Card was deleted.",
        "consent_required": "Please confirm the health-data consent before saving.",
        "shared_with": "Shared appointments",
        "no_shares": "You are not currently sharing this card with any tattoo appointment.",
        "revoke": "Revoke artist access",
        "booking_title": "Health & Safety Card",
        "booking_ready": "You have a private card. Share it with this artist only for this appointment if you want them to review it before the session.",
        "booking_share": "Share my Health & Safety Card with this artist for this tattoo appointment",
        "booking_missing": "You have not created a Health & Safety Card yet.",
        "booking_create": "Create private card",
        "booking_error": "Tatzo could not confirm your health-information sharing choice. Please try again before sending the booking.",
        "artist_title": "Client Health & Safety",
        "artist_intro": "The client explicitly shared this private information for this tattoo appointment. Use it only to discuss tattoo safety; Tatzo does not provide a medical diagnosis.",
        "client_shared": "Your Health & Safety Card is shared with this artist for this appointment.",
        "client_not_shared": "Your Health & Safety Card is not shared with this artist.",
        "share_now": "Share with artist",
        "manage_card": "Manage private card",
        "expires": "Artist access ends after",
        "share_success": "Health & Safety access was shared with the artist.",
        "revoke_success": "Artist access to your Health & Safety Card was revoked.",
        "none_declared": "No relevant items are currently declared on the card.",
    },
    "fr": {
        "nav": "Santé et sécurité",
        "eyebrow": "SANTÉ & SÉCURITÉ PRIVÉES",
        "title": "Partagez uniquement ce qui peut aider à rendre la séance plus sûre.",
        "intro": "Cette fiche privée permet d'indiquer au tatoueur les informations de santé pouvant être pertinentes pour le saignement, les réactions cutanées ou la cicatrisation. Tatzo ne pose aucun diagnostic et ne remplace pas un avis médical.",
        "privacy": "Votre fiche est privée par défaut. Un tatoueur ne la voit que si vous la partagez explicitement pour un rendez-vous de tatouage précis. Vous pouvez retirer l'accès ensuite.",
        "bleeding": "Trouble de saignement ou de coagulation",
        "blood_thinners": "Médicament ou traitement pouvant affecter le saignement",
        "diabetes": "Diabète ou autre trouble de la glycémie",
        "skin": "Affection cutanée pertinente pour le tatouage ou la zone tatouée",
        "allergy": "Allergie ou sensibilité pertinente aux produits de tatouage",
        "immune": "Affection ou traitement pouvant affecter la cicatrisation ou l'immunité",
        "other": "Autre information de santé pertinente pour la sécurité du tatouage",
        "other_help": "Limitez-vous aux informations utiles au tatoueur pour la sécurité. N'ajoutez pas de dossier médical ni de résultats d'examens.",
        "consent": "J'accepte explicitement que Tatzo conserve les informations de santé saisies ici pour la sécurité du tatouage et la gestion des rendez-vous. Je comprends que je peux supprimer cette fiche à tout moment.",
        "save": "Enregistrer la fiche privée",
        "delete": "Supprimer la fiche santé",
        "saved": "Votre fiche privée Santé & Sécurité a été enregistrée.",
        "deleted": "Votre fiche Santé & Sécurité a été supprimée.",
        "consent_required": "Veuillez confirmer le consentement concernant les données de santé avant d'enregistrer.",
        "shared_with": "Rendez-vous partagés",
        "no_shares": "Vous ne partagez actuellement cette fiche avec aucun rendez-vous de tatouage.",
        "revoke": "Retirer l'accès du tatoueur",
        "booking_title": "Fiche Santé & Sécurité",
        "booking_ready": "Vous disposez d'une fiche privée. Vous pouvez la partager avec ce tatoueur uniquement pour ce rendez-vous afin qu'il puisse la consulter avant la séance.",
        "booking_share": "Partager ma fiche Santé & Sécurité avec ce tatoueur pour ce rendez-vous",
        "booking_missing": "Vous n'avez pas encore créé de fiche Santé & Sécurité.",
        "booking_create": "Créer la fiche privée",
        "booking_error": "Tatzo n'a pas pu confirmer votre choix de partage des informations de santé. Réessayez avant d'envoyer la réservation.",
        "artist_title": "Santé & Sécurité du client",
        "artist_intro": "Le client a explicitement partagé ces informations privées pour ce rendez-vous. Utilisez-les uniquement pour discuter de la sécurité du tatouage ; Tatzo ne fournit aucun diagnostic médical.",
        "client_shared": "Votre fiche Santé & Sécurité est partagée avec ce tatoueur pour ce rendez-vous.",
        "client_not_shared": "Votre fiche Santé & Sécurité n'est pas partagée avec ce tatoueur.",
        "share_now": "Partager avec le tatoueur",
        "manage_card": "Gérer la fiche privée",
        "expires": "L'accès du tatoueur prend fin après le",
        "share_success": "L'accès à la fiche Santé & Sécurité a été partagé avec le tatoueur.",
        "revoke_success": "L'accès du tatoueur à votre fiche Santé & Sécurité a été retiré.",
        "none_declared": "Aucun élément pertinent n'est actuellement déclaré sur la fiche.",
    },
    "ru": {
        "nav": "Здоровье и безопасность",
        "eyebrow": "ПРИВАТНО: ЗДОРОВЬЕ И БЕЗОПАСНОСТЬ",
        "title": "Укажите только то, что действительно важно для более безопасного сеанса.",
        "intro": "Эта приватная карточка помогает сообщить тату-мастеру сведения о здоровье, которые могут быть важны для кровотечения, реакции кожи или заживления. Tatzo не ставит диагнозы и не заменяет консультацию врача.",
        "privacy": "По умолчанию карточка видна только вам. Мастер получает доступ только если вы явно поделитесь ею для конкретной записи на тату-сеанс. Доступ можно отозвать позже.",
        "bleeding": "Нарушение кровотечения или свёртывания крови",
        "blood_thinners": "Лекарства или лечение, которые могут влиять на кровотечение",
        "diabetes": "Диабет или другое состояние, связанное с уровнем сахара в крови",
        "skin": "Кожное заболевание, важное для татуировки или выбранной зоны",
        "allergy": "Аллергия или чувствительность, важная для материалов татуировки",
        "immune": "Заболевание или лечение, которое может влиять на иммунитет или заживление",
        "other": "Другие сведения о здоровье, важные для безопасности татуировки",
        "other_help": "Указывайте только информацию, которая нужна мастеру для безопасности татуировки. Не загружайте медицинские карты, анализы или заключения.",
        "consent": "Я явно соглашаюсь на хранение Tatzo указанных здесь сведений о здоровье для безопасности татуировки и сопровождения бронирования. Я понимаю, что могу удалить эту карточку в любой момент.",
        "save": "Сохранить приватную карточку",
        "delete": "Удалить медкарту",
        "saved": "Приватная карточка «Здоровье и безопасность» сохранена.",
        "deleted": "Карточка «Здоровье и безопасность» удалена.",
        "consent_required": "Перед сохранением подтвердите согласие на хранение данных о здоровье.",
        "shared_with": "Записи с доступом",
        "no_shares": "Сейчас карточка не открыта ни для одного тату-сеанса.",
        "revoke": "Отозвать доступ мастера",
        "booking_title": "Здоровье и безопасность",
        "booking_ready": "У вас есть приватная карточка. При желании откройте её этому мастеру только для этой записи, чтобы он мог ознакомиться с важной информацией до сеанса.",
        "booking_share": "Поделиться моей карточкой «Здоровье и безопасность» с этим мастером для этой записи",
        "booking_missing": "Вы ещё не создали карточку «Здоровье и безопасность».",
        "booking_create": "Создать приватную карточку",
        "booking_error": "Tatzo не удалось подтвердить выбор доступа к данным о здоровье. Попробуйте ещё раз перед отправкой бронирования.",
        "artist_title": "Здоровье и безопасность клиента",
        "artist_intro": "Клиент явно поделился этой приватной информацией для конкретной записи. Используйте её только для обсуждения безопасности татуировки; Tatzo не ставит медицинских диагнозов.",
        "client_shared": "Ваша карточка «Здоровье и безопасность» открыта этому мастеру для этой записи.",
        "client_not_shared": "Ваша карточка «Здоровье и безопасность» не открыта этому мастеру.",
        "share_now": "Поделиться с мастером",
        "manage_card": "Управлять приватной карточкой",
        "expires": "Доступ мастера закончится после",
        "share_success": "Доступ к карточке «Здоровье и безопасность» открыт мастеру.",
        "revoke_success": "Доступ мастера к карточке «Здоровье и безопасность» отозван.",
        "none_declared": "В карточке сейчас не отмечены значимые пункты.",
    },
}


def language_code(request):
    language = (getattr(request, "LANGUAGE_CODE", "en") or "en").split("-")[0]
    return language if language in COPY else "en"


def get_copy(request):
    return COPY[language_code(request)]
