# Generated by Django 5.1.7 on 2026-07-05 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("tattoo_session", "Tattoo session"),
                            ("consultation", "Consultation"),
                            ("online_consultation", "Online consultation"),
                        ],
                        default="tattoo_session",
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "session_length_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("client_comfort_limit", models.CharField(blank=True, max_length=40)),
                ("styles", models.JSONField(blank=True, default=list)),
                ("placement", models.CharField(blank=True, max_length=80)),
                ("size", models.CharField(blank=True, max_length=80)),
                ("budget", models.CharField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("ai_ready_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("artist_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentReferenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="appointments/references/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_images",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArtistAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ]
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="ArtistBookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookings_enabled", models.BooleanField(default=True)),
                ("minimum_notice_hours", models.PositiveIntegerField(default=24)),
                ("slot_step_minutes", models.PositiveIntegerField(default=30)),
                ("default_session_minutes", models.PositiveIntegerField(default=60)),
                ("consultation_enabled", models.BooleanField(default=True)),
                ("online_consultation_enabled", models.BooleanField(default=True)),
                (
                    "consultation_required_before_booking",
                    models.BooleanField(default=False),
                ),
                (
                    "consultation_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "online_consultation_price",
                    models.DecimalField(decimal_places=2, default=25, max_digits=8),
                ),
                ("reference_images_required", models.BooleanField(default=False)),
                ("minimum_reference_images", models.PositiveIntegerField(default=1)),
                ("maximum_reference_images", models.PositiveIntegerField(default=10)),
                ("deposit_required", models.BooleanField(default=False)),
                (
                    "deposit_rate",
                    models.DecimalField(decimal_places=2, default=0.3, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistTimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=160)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["artist", "date", "start_time"],
                name="appointment_artist__2e2f8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["client", "-created_at"], name="appointment_client__f75f39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="artistavailability",
            index=models.Index(
                fields=["artist", "weekday"], name="appointment_artist__cac873_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artistavailability",
            unique_together={("artist", "weekday")},
        ),
        migrations.AddIndex(
            model_name="artisttimeoff",
            index=models.Index(
                fields=["artist", "date"], name="appointment_artist__041e2e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artisttimeoff",
            unique_together={("artist", "date")},
        ),
    ]
