# Generated by Django 5.1.7 on 2026-07-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistbookingsettings",
            name="active_styles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="booking_workflow",
            field=models.CharField(
                choices=[("manual", "Manual approval"), ("auto", "Auto accept")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="maximum_booking_window_days",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="maximum_session_hours",
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="phone_consultation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="studio_consultation_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
