# Generated by Django 5.1.7 on 2026-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_artistbookingsettings_active_styles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="consultation_already_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="consultation_note",
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
