# Generated by Django 5.1.7 on 2026-07-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_artistbookingsettings_active_styles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistbookingsettings",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("open", "Booking allowed"),
                    ("paused", "Booking paused"),
                    ("vacation", "Vacation"),
                    ("fully_booked", "Fully booked"),
                    ("consultation_only", "Consultation only"),
                    ("emergency", "Emergency closure"),
                ],
                default="open",
                max_length=30,
            ),
        ),
    ]
