# Generated by Django 5.1.7 on 2026-07-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_artistbookingsettings_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistbookingsettings",
            name="auto_response_booking_approved",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="auto_response_booking_declined",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="auto_response_booking_received",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="auto_response_consultation_required",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="artistbookingsettings",
            name="auto_response_need_more_references",
            field=models.TextField(blank=True, default=""),
        ),
    ]
