# Generated by Django 5.1.7 on 2026-07-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0004_artistbookingsettings_auto_response_booking_approved_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("needs_references", "Need more references"),
                    ("consultation_required", "Consultation required"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
