# Generated by Django 5.1.7 on 2026-07-10 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_appointment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tattoo_session", "Tattoo session"),
                            ("consultation", "Consultation"),
                            ("blocked", "Blocked time"),
                            ("vacation", "Vacation"),
                            ("sketch_deadline", "Sketch deadline"),
                            ("deposit_reminder", "Deposit reminder"),
                            ("healing_reminder", "Healing reminder"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("reschedule_requested", "Reschedule requested"),
                            ("deposit_pending", "Deposit pending"),
                        ],
                        default="planned",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("placement", models.CharField(blank=True, max_length=120)),
                ("tattoo_style", models.CharField(blank=True, max_length=120)),
                (
                    "deposit_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("not_required", "Not required"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_artist_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Artist",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_client_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="appointments.appointment",
                        verbose_name="Related appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="CalendarRescheduleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_start", models.DateTimeField(blank=True, null=True)),
                ("proposed_end", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedule_requests",
                        to="appointments.calendarevent",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_reschedule_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["artist", "starts_at", "ends_at"],
                name="appointment_artist__9dd3ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["client", "starts_at"], name="appointment_client__5abcd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["event_type", "status"], name="appointment_event_t_51689e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarreschedulerequest",
            index=models.Index(
                fields=["event", "status"], name="appointment_event_i_489034_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarreschedulerequest",
            index=models.Index(
                fields=["requested_by", "created_at"],
                name="appointment_request_3ab951_idx",
            ),
        ),
    ]
