# Generated by Django 5.1.7 on 2026-08-03 12:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleMatchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser_session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('target_count', models.PositiveSmallIntegerField(default=30)),
                ('card_order', models.JSONField(default=list)),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('style_scores', models.JSONField(blank=True, default=dict)),
                ('trait_scores', models.JSONField(blank=True, default=dict)),
                ('personality_slug', models.CharField(blank=True, max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_match_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='TattooCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('cloudinary_public_id', models.CharField(max_length=255, unique=True)),
                ('primary_style', models.CharField(choices=[('fine_line', 'Fine Line'), ('minimalism', 'Minimalism'), ('botanical', 'Botanical'), ('ornamental', 'Ornamental'), ('geometric', 'Geometric'), ('dotwork', 'Dotwork'), ('blackwork', 'Blackwork'), ('engraving', 'Engraving'), ('illustrative', 'Illustrative'), ('micro_realism', 'Micro Realism'), ('black_grey_realism', 'Black & Grey Realism'), ('color_realism', 'Color Realism'), ('american_traditional', 'American Traditional'), ('neo_traditional', 'Neo-Traditional'), ('japanese', 'Japanese'), ('watercolor', 'Watercolor'), ('abstract', 'Abstract'), ('cybersigilism', 'Cybersigilism')], max_length=40)),
                ('style_weights', models.JSONField(default=dict)),
                ('visual_traits', models.JSONField(blank=True, default=dict)),
                ('motifs', models.JSONField(blank=True, default=list)),
                ('body_area', models.CharField(blank=True, max_length=80)),
                ('skin_tone', models.CharField(blank=True, max_length=40)),
                ('quality_score', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('card_id',),
                'indexes': [models.Index(fields=['is_active', 'is_approved', 'primary_style'], name='style_match_is_acti_8c8b1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StyleMatchResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('reaction', models.CharField(blank=True, choices=[('reject', 'Not my style'), ('like', 'Like'), ('favorite', 'Favorite')], max_length=16)),
                ('saved', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='style_match.stylematchsession')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='style_match_responses', to='style_match.tattoocard')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddIndex(
            model_name='stylematchsession',
            index=models.Index(fields=['user', 'status', '-started_at'], name='style_match_user_id_db4f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='stylematchsession',
            index=models.Index(fields=['browser_session_key', 'status', '-started_at'], name='style_match_browser_4cfccc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stylematchresponse',
            constraint=models.UniqueConstraint(fields=('session', 'card'), name='unique_style_match_session_card'),
        ),
        migrations.AddConstraint(
            model_name='stylematchresponse',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_style_match_session_position'),
        ),
    ]
