from django.db import migrations

CARDS = {
    "SM003": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762218/style_match/cards/SM003.jpg",
        "cloudinary_public_id": "style_match/cards/SM003",
        "primary_style": "blackwork",
        "style_weights": {
            "blackwork": 0.98,
            "illustrative": 0.68,
            "neo_traditional": 0.42,
            "ornamental": 0.28,
            "engraving": 0.18,
            "japanese": 0.16,
            "fine_line": 0.05,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.92,
            "density": 0.8,
            "contrast": 0.95,
            "realism": 0.28,
            "organic": 0.76,
            "geometric": 0.2,
            "symmetry": 0.25,
        },
        "motifs": ["wyvern", "dragon", "mythological", "river", "wings"],
        "body_area": "shoulder blade and upper back",
        "skin_tone": "medium",
        "quality_score": 0.93,
        "is_active": True,
        "is_approved": True,
    },
    "SM004": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762455/style_match/cards/SM004.jpg",
        "cloudinary_public_id": "style_match/cards/SM004",
        "primary_style": "color_realism",
        "style_weights": {
            "color_realism": 0.98,
            "black_grey_realism": 0.46,
            "illustrative": 0.4,
            "botanical": 0.34,
            "watercolor": 0.24,
            "micro_realism": 0.16,
            "fine_line": 0.04,
        },
        "visual_traits": {
            "color": 0.95,
            "line_weight": 0.22,
            "density": 0.88,
            "contrast": 0.76,
            "realism": 0.96,
            "organic": 0.92,
            "geometric": 0.08,
            "symmetry": 0.12,
        },
        "motifs": [
            "volcanic coastline",
            "dawn",
            "pine tree",
            "ocean",
            "cliffs",
            "mist",
            "landscape",
        ],
        "body_area": "outer calf",
        "skin_tone": "medium-light",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM005": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762680/style_match/cards/SM005.jpg",
        "cloudinary_public_id": "style_match/cards/SM005",
        "primary_style": "ornamental",
        "style_weights": {
            "ornamental": 0.98,
            "dotwork": 0.9,
            "botanical": 0.62,
            "abstract": 0.55,
            "fine_line": 0.42,
            "geometric": 0.35,
            "blackwork": 0.2,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.35,
            "density": 0.7,
            "contrast": 0.58,
            "realism": 0.05,
            "organic": 0.85,
            "geometric": 0.55,
            "symmetry": 0.94,
        },
        "motifs": [
            "abstract botanical ornament",
            "filigree",
            "leaves",
            "arabesque",
            "symmetrical ornament",
        ],
        "body_area": "side ribcage",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM006": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763169/style_match/cards/SM006.jpg",
        "cloudinary_public_id": "style_match/cards/SM006",
        "primary_style": "american_traditional",
        "style_weights": {
            "american_traditional": 0.98,
            "illustrative": 0.72,
            "neo_traditional": 0.4,
            "ornamental": 0.28,
            "blackwork": 0.18,
            "dotwork": 0.1,
            "color_realism": 0.05,
        },
        "visual_traits": {
            "color": 0.86,
            "line_weight": 0.88,
            "density": 0.62,
            "contrast": 0.84,
            "realism": 0.08,
            "organic": 0.58,
            "geometric": 0.34,
            "symmetry": 0.72,
        },
        "motifs": [
            "storm lantern",
            "flame",
            "wind",
            "wind swirls",
            "fire",
        ],
        "body_area": "outer thigh",
        "skin_tone": "medium",
        "quality_score": 0.95,
        "is_active": True,
        "is_approved": True,
    },
    "SM007": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763475/style_match/cards/SM007.jpg",
        "cloudinary_public_id": "style_match/cards/SM007",
        "primary_style": "geometric",
        "style_weights": {
            "geometric": 0.98,
            "minimalism": 0.94,
            "fine_line": 0.62,
            "blackwork": 0.32,
            "abstract": 0.28,
            "ornamental": 0.12,
            "dotwork": 0.04,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.24,
            "density": 0.17,
            "contrast": 0.91,
            "realism": 0.01,
            "organic": 0.06,
            "geometric": 0.98,
            "symmetry": 0.88,
        },
        "motifs": [
            "solar eclipse",
            "orbital arcs",
            "planet",
            "stars",
            "celestial",
        ],
        "body_area": "outer ankle",
        "skin_tone": "medium-dark",
        "quality_score": 0.95,
        "is_active": True,
        "is_approved": True,
    },
    "SM008": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763726/style_match/cards/SM008.jpg",
        "cloudinary_public_id": "style_match/cards/SM008",
        "primary_style": "black_grey_realism",
        "style_weights": {
            "black_grey_realism": 0.99,
            "micro_realism": 0.72,
            "illustrative": 0.32,
            "fine_line": 0.28,
            "abstract": 0.24,
            "blackwork": 0.22,
            "engraving": 0.08,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.32,
            "density": 0.76,
            "contrast": 0.88,
            "realism": 0.99,
            "organic": 0.9,
            "geometric": 0.16,
            "symmetry": 0.82,
        },
        "motifs": [
            "human eye",
            "reflection",
            "desert dunes",
            "lone silhouette",
            "horizon",
        ],
        "body_area": "outer forearm",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
}


def seed_card_library(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    for card_id, defaults in CARDS.items():
        TattooCard.objects.update_or_create(card_id=card_id, defaults=defaults)


def remove_card_library(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    TattooCard.objects.filter(card_id__in=CARDS).delete()


class Migration(migrations.Migration):
    dependencies = [("style_match", "0003_seed_sm002")]

    operations = [migrations.RunPython(seed_card_library, remove_card_library)]
