from django.db import migrations

CARDS = {
    "SM003": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762218/style_match/cards/SM003.jpg",
        "cloudinary_public_id": "style_match/cards/SM003",
        "primary_style": "blackwork",
        "style_weights": {
            "blackwork": 0.98,
            "illustrative": 0.68,
            "neo_traditional": 0.42,
            "ornamental": 0.28,
            "engraving": 0.18,
            "japanese": 0.16,
            "fine_line": 0.05,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.92,
            "density": 0.8,
            "contrast": 0.95,
            "realism": 0.28,
            "organic": 0.76,
            "geometric": 0.2,
            "symmetry": 0.25,
        },
        "motifs": ["wyvern", "dragon", "mythological", "river", "wings"],
        "body_area": "shoulder blade and upper back",
        "skin_tone": "medium",
        "quality_score": 0.93,
        "is_active": True,
        "is_approved": True,
    },
    "SM004": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762455/style_match/cards/SM004.jpg",
        "cloudinary_public_id": "style_match/cards/SM004",
        "primary_style": "color_realism",
        "style_weights": {
            "color_realism": 0.98,
            "black_grey_realism": 0.46,
            "illustrative": 0.4,
            "botanical": 0.34,
            "watercolor": 0.24,
            "micro_realism": 0.16,
            "fine_line": 0.04,
        },
        "visual_traits": {
            "color": 0.95,
            "line_weight": 0.22,
            "density": 0.88,
            "contrast": 0.76,
            "realism": 0.96,
            "organic": 0.92,
            "geometric": 0.08,
            "symmetry": 0.12,
        },
        "motifs": [
            "volcanic coastline",
            "dawn",
            "pine tree",
            "ocean",
            "cliffs",
            "mist",
            "landscape",
        ],
        "body_area": "outer calf",
        "skin_tone": "medium-light",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM005": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762680/style_match/cards/SM005.jpg",
        "cloudinary_public_id": "style_match/cards/SM005",
        "primary_style": "ornamental",
        "style_weights": {
            "ornamental": 0.98,
            "dotwork": 0.9,
            "botanical": 0.62,
            "abstract": 0.55,
            "fine_line": 0.42,
            "geometric": 0.35,
            "blackwork": 0.2,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.35,
            "density": 0.7,
            "contrast": 0.58,
            "realism": 0.05,
            "organic": 0.85,
            "geometric": 0.55,
            "symmetry": 0.94,
        },
        "motifs": [
            "abstract botanical ornament",
            "filigree",
            "leaves",
            "arabesque",
            "symmetrical ornament",
        ],
        "body_area": "side ribcage",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM006": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763169/style_match/cards/SM006.jpg",
        "cloudinary_public_id": "style_match/cards/SM006",
        "primary_style": "american_traditional",
        "style_weights": {
            "american_traditional": 0.98,
            "illustrative": 0.72,
            "neo_traditional": 0.4,
            "ornamental": 0.28,
            "blackwork": 0.18,
            "dotwork": 0.1,
            "color_realism": 0.05,
        },
        "visual_traits": {
            "color": 0.86,
            "line_weight": 0.88,
            "density": 0.62,
            "contrast": 0.84,
            "realism": 0.08,
            "organic": 0.58,
            "geometric": 0.34,
            "symmetry": 0.72,
        },
        "motifs": [
            "storm lantern",
            "flame",
            "wind",
            "wind swirls",
            "fire",
        ],
        "body_area": "outer thigh",
        "skin_tone": "medium",
        "quality_score": 0.95,
        "is_active": True,
        "is_approved": True,
    },
    "SM007": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763475/style_match/cards/SM007.jpg",
        "cloudinary_public_id": "style_match/cards/SM007",
        "primary_style": "geometric",
        "style_weights": {
            "geometric": 0.98,
            "minimalism": 0.94,
            "fine_line": 0.62,
            "blackwork": 0.32,
            "abstract": 0.28,
            "ornamental": 0.12,
            "dotwork": 0.04,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.24,
            "density": 0.17,
            "contrast": 0.91,
            "realism": 0.01,
            "organic": 0.06,
            "geometric": 0.98,
            "symmetry": 0.88,
        },
        "motifs": [
            "solar eclipse",
            "orbital arcs",
            "planet",
            "stars",
            "celestial",
        ],
        "body_area": "outer ankle",
        "skin_tone": "medium-dark",
        "quality_score": 0.95,
        "is_active": True,
        "is_approved": True,
    },
    "SM008": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763726/style_match/cards/SM008.jpg",
        "cloudinary_public_id": "style_match/cards/SM008",
        "primary_style": "black_grey_realism",
        "style_weights": {
            "black_grey_realism": 0.99,
            "micro_realism": 0.72,
            "illustrative": 0.32,
            "fine_line": 0.28,
            "abstract": 0.24,
            "blackwork": 0.22,
            "engraving": 0.08,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.32,
            "density": 0.76,
            "contrast": 0.88,
            "realism": 0.99,
            "organic": 0.9,
            "geometric": 0.16,
            "symmetry": 0.82,
        },
        "motifs": [
            "human eye",
            "reflection",
            "desert dunes",
            "lone silhouette",
            "horizon",
        ],
        "body_area": "outer forearm",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM009": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763998/style_match/cards/SM009.jpg",
        "cloudinary_public_id": "style_match/cards/SM009",
        "primary_style": "watercolor",
        "style_weights": {
            "watercolor": 0.99,
            "abstract": 0.91,
            "illustrative": 0.58,
            "ornamental": 0.34,
            "fine_line": 0.28,
            "color_realism": 0.16,
            "minimalism": 0.08,
        },
        "visual_traits": {
            "color": 0.98,
            "line_weight": 0.22,
            "density": 0.56,
            "contrast": 0.74,
            "realism": 0.08,
            "organic": 0.98,
            "geometric": 0.05,
            "symmetry": 0.18,
        },
        "motifs": [
            "flame",
            "ocean wave",
            "wind",
            "water",
            "fire",
            "transformation",
        ],
        "body_area": "front shin",
        "skin_tone": "light",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM010": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785764262/style_match/cards/SM010.jpg",
        "cloudinary_public_id": "style_match/cards/SM010",
        "primary_style": "engraving",
        "style_weights": {
            "engraving": 0.99,
            "illustrative": 0.72,
            "fine_line": 0.62,
            "ornamental": 0.48,
            "dotwork": 0.38,
            "botanical": 0.32,
            "black_grey_realism": 0.2,
            "blackwork": 0.16,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.28,
            "density": 0.74,
            "contrast": 0.73,
            "realism": 0.55,
            "organic": 0.99,
            "geometric": 0.06,
            "symmetry": 0.72,
        },
        "motifs": [
            "deep-sea jellyfish",
            "kelp",
            "tentacles",
            "ocean",
            "marine life",
        ],
        "body_area": "lower back",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM011": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785764733/style_match/cards/SM011.jpg",
        "cloudinary_public_id": "style_match/cards/SM011",
        "primary_style": "botanical",
        "style_weights": {
            "botanical": 0.99,
            "fine_line": 0.78,
            "illustrative": 0.54,
            "ornamental": 0.42,
            "watercolor": 0.26,
            "color_realism": 0.24,
            "engraving": 0.18,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.52,
            "line_weight": 0.22,
            "density": 0.48,
            "contrast": 0.52,
            "realism": 0.52,
            "organic": 0.99,
            "geometric": 0.04,
            "symmetry": 0.35,
        },
        "motifs": [
            "night-blooming cereus",
            "flower",
            "flower buds",
            "leaves",
            "botanical stem",
        ],
        "body_area": "sternum and upper abdomen",
        "skin_tone": "medium-dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM012": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785765232/style_match/cards/SM012.jpg",
        "cloudinary_public_id": "style_match/cards/SM012",
        "primary_style": "micro_realism",
        "style_weights": {
            "micro_realism": 0.99,
            "minimalism": 0.92,
            "fine_line": 0.62,
            "color_realism": 0.58,
            "geometric": 0.44,
            "illustrative": 0.35,
            "abstract": 0.3,
        },
        "visual_traits": {
            "color": 0.55,
            "line_weight": 0.2,
            "density": 0.26,
            "contrast": 0.56,
            "realism": 0.88,
            "organic": 0.42,
            "geometric": 0.76,
            "symmetry": 0.91,
        },
        "motifs": [
            "hourglass",
            "sand",
            "ocean wave",
            "time",
            "transformation",
            "glass",
        ],
        "body_area": "inner upper arm",
        "skin_tone": "medium",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM013": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785765879/style_match/cards/SM013.jpg",
        "cloudinary_public_id": "style_match/cards/SM013",
        "primary_style": "dotwork",
        "style_weights": {
            "dotwork": 0.99,
            "engraving": 0.72,
            "fine_line": 0.68,
            "illustrative": 0.64,
            "black_grey_realism": 0.44,
            "geometric": 0.28,
            "blackwork": 0.24,
            "ornamental": 0.18,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.22,
            "density": 0.76,
            "contrast": 0.66,
            "realism": 0.64,
            "organic": 0.9,
            "geometric": 0.4,
            "symmetry": 0.96,
        },
        "motifs": [
            "cicada",
            "insect",
            "wings",
            "entomology",
            "stippling",
        ],
        "body_area": "back of upper arm",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM014": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785766609/style_match/cards/SM014.jpg",
        "cloudinary_public_id": "style_match/cards/SM014",
        "primary_style": "japanese",
        "style_weights": {
            "japanese": 0.99,
            "illustrative": 0.86,
            "neo_traditional": 0.62,
            "botanical": 0.44,
            "ornamental": 0.4,
            "american_traditional": 0.28,
            "color_realism": 0.18,
            "engraving": 0.12,
        },
        "visual_traits": {
            "color": 0.9,
            "line_weight": 0.55,
            "density": 0.82,
            "contrast": 0.78,
            "realism": 0.35,
            "organic": 0.94,
            "geometric": 0.08,
            "symmetry": 0.22,
        },
        "motifs": [
            "red fox",
            "kitsune",
            "ocean waves",
            "wind",
            "maple leaves",
            "autumn",
        ],
        "body_area": "front-outer thigh",
        "skin_tone": "light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM015": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785766634/style_match/cards/SM015.jpg",
        "cloudinary_public_id": "style_match/cards/SM015",
        "primary_style": "minimalism",
        "style_weights": {
            "minimalism": 0.99,
            "fine_line": 0.86,
            "abstract": 0.68,
            "illustrative": 0.38,
            "geometric": 0.24,
            "blackwork": 0.08,
            "ornamental": 0.06,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.14,
            "density": 0.07,
            "contrast": 0.72,
            "realism": 0.02,
            "organic": 0.48,
            "geometric": 0.25,
            "symmetry": 0.14,
        },
        "motifs": [
            "human silhouette",
            "wind",
            "motion",
            "resilience",
            "minimal line figure",
        ],
        "body_area": "upper chest below collarbone",
        "skin_tone": "dark",
        "quality_score": 0.95,
        "is_active": True,
        "is_approved": True,
    },
    "SM016": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785767279/style_match/cards/SM016.jpg",
        "cloudinary_public_id": "style_match/cards/SM016",
        "primary_style": "illustrative",
        "style_weights": {
            "illustrative": 0.99,
            "fine_line": 0.8,
            "neo_traditional": 0.58,
            "engraving": 0.52,
            "abstract": 0.48,
            "american_traditional": 0.25,
            "watercolor": 0.22,
            "color_realism": 0.18,
        },
        "visual_traits": {
            "color": 0.72,
            "line_weight": 0.34,
            "density": 0.74,
            "contrast": 0.64,
            "realism": 0.42,
            "organic": 0.92,
            "geometric": 0.08,
            "symmetry": 0.18,
        },
        "motifs": [
            "surreal portrait",
            "woman profile",
            "three swallows",
            "flowing hair",
            "flight",
            "freedom",
        ],
        "body_area": "shoulder blade",
        "skin_tone": "medium",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM017": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785767796/style_match/cards/SM017.jpg",
        "cloudinary_public_id": "style_match/cards/SM017",
        "primary_style": "abstract",
        "style_weights": {
            "abstract": 0.99,
            "cybersigilism": 0.84,
            "geometric": 0.72,
            "ornamental": 0.58,
            "illustrative": 0.34,
            "neo_traditional": 0.24,
            "blackwork": 0.18,
            "watercolor": 0.12,
        },
        "visual_traits": {
            "color": 0.88,
            "line_weight": 0.45,
            "density": 0.68,
            "contrast": 0.78,
            "realism": 0.01,
            "organic": 0.8,
            "geometric": 0.72,
            "symmetry": 0.16,
        },
        "motifs": [
            "asymmetrical colored vortex",
            "interlocking curves",
            "sharp arcs",
            "flowing ribbons",
            "spiral",
            "kinetic motion",
        ],
        "body_area": "outer shoulder and deltoid",
        "skin_tone": "medium-dark",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
}


def seed_card_library(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    for card_id, defaults in CARDS.items():
        TattooCard.objects.update_or_create(card_id=card_id, defaults=defaults)


def remove_card_library(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    TattooCard.objects.filter(card_id__in=CARDS).delete()


class Migration(migrations.Migration):
    dependencies = [("style_match", "0003_seed_sm002")]

    operations = [migrations.RunPython(seed_card_library, remove_card_library)]
