from django.db import migrations

CARDS = {
    "SM003": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762218/style_match/cards/SM003.jpg",
        "cloudinary_public_id": "style_match/cards/SM003",
        "primary_style": "blackwork",
        "style_weights": {
            "blackwork": 0.98,
            "illustrative": 0.68,
            "neo_traditional": 0.42,
            "ornamental": 0.28,
            "engraving": 0.18,
            "japanese": 0.16,
            "fine_line": 0.05,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.92,
            "density": 0.8,
            "contrast": 0.95,
            "realism": 0.28,
            "organic": 0.76,
            "geometric": 0.2,
            "symmetry": 0.25,
        },
        "motifs": ["wyvern", "dragon", "mythological", "river", "wings"],
        "body_area": "shoulder blade and upper back",
        "skin_tone": "medium",
        "quality_score": 0.93,
        "is_active": True,
        "is_approved": True,
    },
    "SM004": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762455/style_match/cards/SM004.jpg",
        "cloudinary_public_id": "style_match/cards/SM004",
        "primary_style": "color_realism",
        "style_weights": {
            "color_realism": 0.98,
            "black_grey_realism": 0.46,
            "illustrative": 0.4,
            "botanical": 0.34,
            "watercolor": 0.24,
            "micro_realism": 0.16,
            "fine_line": 0.04,
        },
        "visual_traits": {
            "color": 0.95,
            "line_weight": 0.22,
            "density": 0.88,
            "contrast": 0.76,
            "realism": 0.96,
            "organic": 0.92,
            "geometric": 0.08,
            "symmetry": 0.12,
        },
        "motifs": [
            "volcanic coastline",
            "dawn",
            "pine tree",
            "ocean",
            "cliffs",
            "mist",
            "landscape",
        ],
        "body_area": "outer calf",
        "skin_tone": "medium-light",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM005": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785762680/style_match/cards/SM005.jpg",
        "cloudinary_public_id": "style_match/cards/SM005",
        "primary_style": "ornamental",
        "style_weights": {
            "ornamental": 0.98,
            "dotwork": 0.9,
            "botanical": 0.62,
            "abstract": 0.55,
            "fine_line": 0.42,
            "geometric": 0.35,
            "blackwork": 0.2,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.35,
            "density": 0.7,
            "contrast": 0.58,
            "realism": 0.05,
            "organic": 0.85,
            "geometric": 0.55,
            "symmetry": 0.94,
        },
        "motifs": [
            "abstract botanical ornament",
            "filigree",
            "leaves",
            "arabesque",
            "symmetrical ornament",
        ],
        "body_area": "side ribcage",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM006": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763169/style_match/cards/SM006.jpg",
        "cloudinary_public_id": "style_match/cards/SM006",
        "primary_style": "american_traditional",
        "style_weights": {
            "american_traditional": 0.98,
            "illustrative": 0.72,
            "neo_traditional": 0.4,
            "ornamental": 0.28,
            "blackwork": 0.18,
            "dotwork": 0.1,
            "color_realism": 0.05,
        },
        "visual_traits": {
            "color": 0.86,
            "line_weight": 0.88,
            "density": 0.62,
            "contrast": 0.84,
            "realism": 0.08,
            "organic": 0.58,
            "geometric": 0.34,
            "symmetry": 0.72,
        },
        "motifs": [
            "storm lantern",
            "flame",
            "wind",
            "wind swirls",
            "fire",
        ],
        "body_area": "outer thigh",
        "skin_tone": "medium",
        "quality_score": 0.95,
        "is_active": True,
        "is_approved": True,
    },
    "SM007": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763475/style_match/cards/SM007.jpg",
        "cloudinary_public_id": "style_match/cards/SM007",
        "primary_style": "geometric",
        "style_weights": {
            "geometric": 0.98,
            "minimalism": 0.94,
            "fine_line": 0.62,
            "blackwork": 0.32,
            "abstract": 0.28,
            "ornamental": 0.12,
            "dotwork": 0.04,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.24,
            "density": 0.17,
            "contrast": 0.91,
            "realism": 0.01,
            "organic": 0.06,
            "geometric": 0.98,
            "symmetry": 0.88,
        },
        "motifs": [
            "solar eclipse",
            "orbital arcs",
            "planet",
            "stars",
            "celestial",
        ],
        "body_area": "outer ankle",
        "skin_tone": "medium-dark",
        "quality_score": 0.95,
        "is_active": True,
        "is_approved": True,
    },
    "SM008": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763726/style_match/cards/SM008.jpg",
        "cloudinary_public_id": "style_match/cards/SM008",
        "primary_style": "black_grey_realism",
        "style_weights": {
            "black_grey_realism": 0.99,
            "micro_realism": 0.72,
            "illustrative": 0.32,
            "fine_line": 0.28,
            "abstract": 0.24,
            "blackwork": 0.22,
            "engraving": 0.08,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.32,
            "density": 0.76,
            "contrast": 0.88,
            "realism": 0.99,
            "organic": 0.9,
            "geometric": 0.16,
            "symmetry": 0.82,
        },
        "motifs": [
            "human eye",
            "reflection",
            "desert dunes",
            "lone silhouette",
            "horizon",
        ],
        "body_area": "outer forearm",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM009": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785763998/style_match/cards/SM009.jpg",
        "cloudinary_public_id": "style_match/cards/SM009",
        "primary_style": "watercolor",
        "style_weights": {
            "watercolor": 0.99,
            "abstract": 0.91,
            "illustrative": 0.58,
            "ornamental": 0.34,
            "fine_line": 0.28,
            "color_realism": 0.16,
            "minimalism": 0.08,
        },
        "visual_traits": {
            "color": 0.98,
            "line_weight": 0.22,
            "density": 0.56,
            "contrast": 0.74,
            "realism": 0.08,
            "organic": 0.98,
            "geometric": 0.05,
            "symmetry": 0.18,
        },
        "motifs": [
            "flame",
            "ocean wave",
            "wind",
            "water",
            "fire",
            "transformation",
        ],
        "body_area": "front shin",
        "skin_tone": "light",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM010": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785764262/style_match/cards/SM010.jpg",
        "cloudinary_public_id": "style_match/cards/SM010",
        "primary_style": "engraving",
        "style_weights": {
            "engraving": 0.99,
            "illustrative": 0.72,
            "fine_line": 0.62,
            "ornamental": 0.48,
            "dotwork": 0.38,
            "botanical": 0.32,
            "black_grey_realism": 0.2,
            "blackwork": 0.16,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.28,
            "density": 0.74,
            "contrast": 0.73,
            "realism": 0.55,
            "organic": 0.99,
            "geometric": 0.06,
            "symmetry": 0.72,
        },
        "motifs": [
            "deep-sea jellyfish",
            "kelp",
            "tentacles",
            "ocean",
            "marine life",
        ],
        "body_area": "lower back",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM011": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785764733/style_match/cards/SM011.jpg",
        "cloudinary_public_id": "style_match/cards/SM011",
        "primary_style": "botanical",
        "style_weights": {
            "botanical": 0.99,
            "fine_line": 0.78,
            "illustrative": 0.54,
            "ornamental": 0.42,
            "watercolor": 0.26,
            "color_realism": 0.24,
            "engraving": 0.18,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.52,
            "line_weight": 0.22,
            "density": 0.48,
            "contrast": 0.52,
            "realism": 0.52,
            "organic": 0.99,
            "geometric": 0.04,
            "symmetry": 0.35,
        },
        "motifs": [
            "night-blooming cereus",
            "flower",
            "flower buds",
            "leaves",
            "botanical stem",
        ],
        "body_area": "sternum and upper abdomen",
        "skin_tone": "medium-dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM012": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785765232/style_match/cards/SM012.jpg",
        "cloudinary_public_id": "style_match/cards/SM012",
        "primary_style": "micro_realism",
        "style_weights": {
            "micro_realism": 0.99,
            "minimalism": 0.92,
            "fine_line": 0.62,
            "color_realism": 0.58,
            "geometric": 0.44,
            "illustrative": 0.35,
            "abstract": 0.3,
        },
        "visual_traits": {
            "color": 0.55,
            "line_weight": 0.2,
            "density": 0.26,
            "contrast": 0.56,
            "realism": 0.88,
            "organic": 0.42,
            "geometric": 0.76,
            "symmetry": 0.91,
        },
        "motifs": [
            "hourglass",
            "sand",
            "ocean wave",
            "time",
            "transformation",
            "glass",
        ],
        "body_area": "inner upper arm",
        "skin_tone": "medium",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM013": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785765879/style_match/cards/SM013.jpg",
        "cloudinary_public_id": "style_match/cards/SM013",
        "primary_style": "dotwork",
        "style_weights": {
            "dotwork": 0.99,
            "engraving": 0.72,
            "fine_line": 0.68,
            "illustrative": 0.64,
            "black_grey_realism": 0.44,
            "geometric": 0.28,
            "blackwork": 0.24,
            "ornamental": 0.18,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.22,
            "density": 0.76,
            "contrast": 0.66,
            "realism": 0.64,
            "organic": 0.9,
            "geometric": 0.4,
            "symmetry": 0.96,
        },
        "motifs": [
            "cicada",
            "insect",
            "wings",
            "entomology",
            "stippling",
        ],
        "body_area": "back of upper arm",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM014": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785766609/style_match/cards/SM014.jpg",
        "cloudinary_public_id": "style_match/cards/SM014",
        "primary_style": "japanese",
        "style_weights": {
            "japanese": 0.99,
            "illustrative": 0.86,
            "neo_traditional": 0.62,
            "botanical": 0.44,
            "ornamental": 0.4,
            "american_traditional": 0.28,
            "color_realism": 0.18,
            "engraving": 0.12,
        },
        "visual_traits": {
            "color": 0.9,
            "line_weight": 0.55,
            "density": 0.82,
            "contrast": 0.78,
            "realism": 0.35,
            "organic": 0.94,
            "geometric": 0.08,
            "symmetry": 0.22,
        },
        "motifs": [
            "red fox",
            "kitsune",
            "ocean waves",
            "wind",
            "maple leaves",
            "autumn",
        ],
        "body_area": "front-outer thigh",
        "skin_tone": "light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM015": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785766634/style_match/cards/SM015.jpg",
        "cloudinary_public_id": "style_match/cards/SM015",
        "primary_style": "minimalism",
        "style_weights": {
            "minimalism": 0.99,
            "fine_line": 0.86,
            "abstract": 0.68,
            "illustrative": 0.38,
            "geometric": 0.24,
            "blackwork": 0.08,
            "ornamental": 0.06,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.14,
            "density": 0.07,
            "contrast": 0.72,
            "realism": 0.02,
            "organic": 0.48,
            "geometric": 0.25,
            "symmetry": 0.14,
        },
        "motifs": [
            "human silhouette",
            "wind",
            "motion",
            "resilience",
            "minimal line figure",
        ],
        "body_area": "upper chest below collarbone",
        "skin_tone": "dark",
        "quality_score": 0.95,
        "is_active": True,
        "is_approved": True,
    },
    "SM016": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785767279/style_match/cards/SM016.jpg",
        "cloudinary_public_id": "style_match/cards/SM016",
        "primary_style": "illustrative",
        "style_weights": {
            "illustrative": 0.99,
            "fine_line": 0.8,
            "neo_traditional": 0.58,
            "engraving": 0.52,
            "abstract": 0.48,
            "american_traditional": 0.25,
            "watercolor": 0.22,
            "color_realism": 0.18,
        },
        "visual_traits": {
            "color": 0.72,
            "line_weight": 0.34,
            "density": 0.74,
            "contrast": 0.64,
            "realism": 0.42,
            "organic": 0.92,
            "geometric": 0.08,
            "symmetry": 0.18,
        },
        "motifs": [
            "surreal portrait",
            "woman profile",
            "three swallows",
            "flowing hair",
            "flight",
            "freedom",
        ],
        "body_area": "shoulder blade",
        "skin_tone": "medium",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM017": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785767796/style_match/cards/SM017.jpg",
        "cloudinary_public_id": "style_match/cards/SM017",
        "primary_style": "abstract",
        "style_weights": {
            "abstract": 0.99,
            "cybersigilism": 0.84,
            "geometric": 0.72,
            "ornamental": 0.58,
            "illustrative": 0.34,
            "neo_traditional": 0.24,
            "blackwork": 0.18,
            "watercolor": 0.12,
        },
        "visual_traits": {
            "color": 0.88,
            "line_weight": 0.45,
            "density": 0.68,
            "contrast": 0.78,
            "realism": 0.01,
            "organic": 0.8,
            "geometric": 0.72,
            "symmetry": 0.16,
        },
        "motifs": [
            "asymmetrical colored vortex",
            "interlocking curves",
            "sharp arcs",
            "flowing ribbons",
            "spiral",
            "kinetic motion",
        ],
        "body_area": "outer shoulder and deltoid",
        "skin_tone": "medium-dark",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM018": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785768574/style_match/cards/SM018.jpg",
        "cloudinary_public_id": "style_match/cards/SM018",
        "primary_style": "cybersigilism",
        "style_weights": {
            "cybersigilism": 0.99,
            "blackwork": 0.86,
            "ornamental": 0.72,
            "geometric": 0.62,
            "abstract": 0.58,
            "fine_line": 0.32,
            "dotwork": 0.18,
            "engraving": 0.14,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.48,
            "density": 0.72,
            "contrast": 0.86,
            "realism": 0.03,
            "organic": 0.82,
            "geometric": 0.72,
            "symmetry": 0.96,
        },
        "motifs": [
            "biomechanical thorn lattice",
            "thorns",
            "spinal axis",
            "exoskeleton",
            "web",
            "sigil",
        ],
        "body_area": "central upper and mid-back",
        "skin_tone": "light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM019": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785768899/style_match/cards/SM019.jpg",
        "cloudinary_public_id": "style_match/cards/SM019",
        "primary_style": "blackwork",
        "style_weights": {
            "blackwork": 0.99,
            "botanical": 0.9,
            "illustrative": 0.72,
            "fine_line": 0.58,
            "engraving": 0.44,
            "ornamental": 0.36,
            "dotwork": 0.3,
            "neo_traditional": 0.18,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.52,
            "density": 0.66,
            "contrast": 0.84,
            "realism": 0.48,
            "organic": 0.96,
            "geometric": 0.1,
            "symmetry": 0.34,
        },
        "motifs": [
            "carnivorous pitcher plant",
            "nepenthes",
            "pitchers",
            "leaves",
            "vines",
            "botanical tendrils",
        ],
        "body_area": "back of calf",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM020": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785769374/style_match/cards/SM020.jpg",
        "cloudinary_public_id": "style_match/cards/SM020",
        "primary_style": "watercolor",
        "style_weights": {
            "watercolor": 0.99,
            "botanical": 0.94,
            "fine_line": 0.48,
            "minimalism": 0.44,
            "illustrative": 0.38,
            "color_realism": 0.22,
            "abstract": 0.18,
            "micro_realism": 0.12,
        },
        "visual_traits": {
            "color": 0.78,
            "line_weight": 0.12,
            "density": 0.34,
            "contrast": 0.32,
            "realism": 0.52,
            "organic": 0.98,
            "geometric": 0.02,
            "symmetry": 0.18,
        },
        "motifs": [
            "magnolia branch",
            "magnolia flowers",
            "petals",
            "leaves",
            "botanical stem",
            "pastel wash",
        ],
        "body_area": "inner forearm",
        "skin_tone": "medium-light",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM021": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785776927/style_match/cards/SM021.jpg",
        "cloudinary_public_id": "style_match/cards/SM021",
        "primary_style": "american_traditional",
        "style_weights": {
            "american_traditional": 0.99,
            "neo_traditional": 0.62,
            "illustrative": 0.5,
            "blackwork": 0.42,
            "botanical": 0.24,
            "minimalism": 0.18,
            "fine_line": 0.12,
            "japanese": 0.08,
        },
        "visual_traits": {
            "color": 0.72,
            "line_weight": 0.68,
            "density": 0.48,
            "contrast": 0.86,
            "realism": 0.18,
            "organic": 0.88,
            "geometric": 0.12,
            "symmetry": 0.22,
        },
        "motifs": [
            "swallow",
            "olive branch",
            "bird in flight",
            "peace",
            "freedom",
            "red breast",
        ],
        "body_area": "upper chest",
        "skin_tone": "dark",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM022": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785779326/style_match/cards/SM022.jpg",
        "cloudinary_public_id": "style_match/cards/SM022",
        "primary_style": "engraving",
        "style_weights": {
            "engraving": 0.99,
            "geometric": 0.9,
            "fine_line": 0.78,
            "illustrative": 0.68,
            "dotwork": 0.44,
            "black_grey_realism": 0.28,
            "ornamental": 0.24,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.18,
            "density": 0.75,
            "contrast": 0.66,
            "realism": 0.58,
            "organic": 0.18,
            "geometric": 0.98,
            "symmetry": 0.96,
        },
        "motifs": [
            "cutaway observatory tower",
            "spiral staircase",
            "glass dome",
            "architectural blueprint",
            "construction lines",
            "circles",
        ],
        "body_area": "side ribcage",
        "skin_tone": "light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM023": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785779913/style_match/cards/SM023.jpg",
        "cloudinary_public_id": "style_match/cards/SM023",
        "primary_style": "micro_realism",
        "style_weights": {
            "micro_realism": 0.99,
            "color_realism": 0.88,
            "botanical": 0.62,
            "minimalism": 0.46,
            "illustrative": 0.32,
            "fine_line": 0.24,
            "watercolor": 0.18,
            "neo_traditional": 0.08,
        },
        "visual_traits": {
            "color": 0.68,
            "line_weight": 0.12,
            "density": 0.28,
            "contrast": 0.56,
            "realism": 0.96,
            "organic": 0.98,
            "geometric": 0.03,
            "symmetry": 0.42,
        },
        "motifs": [
            "tree frog",
            "rain-wet leaf",
            "water droplets",
            "tropical nature",
            "amphibian",
            "miniature wildlife",
        ],
        "body_area": "outer ankle",
        "skin_tone": "medium-dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM024": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785780541/style_match/cards/SM024.jpg",
        "cloudinary_public_id": "style_match/cards/SM024",
        "primary_style": "fine_line",
        "style_weights": {
            "fine_line": 0.99,
            "dotwork": 0.78,
            "minimalism": 0.72,
            "illustrative": 0.52,
            "geometric": 0.44,
            "micro_realism": 0.18,
            "engraving": 0.16,
            "abstract": 0.14,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.1,
            "density": 0.16,
            "contrast": 0.44,
            "realism": 0.36,
            "organic": 0.62,
            "geometric": 0.48,
            "symmetry": 0.2,
        },
        "motifs": [
            "open hand",
            "paper boat",
            "support",
            "care",
            "balance",
            "fragility",
        ],
        "body_area": "shoulder blade",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM025": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785781066/style_match/cards/SM025.jpg",
        "cloudinary_public_id": "style_match/cards/SM025",
        "primary_style": "color_realism",
        "style_weights": {
            "color_realism": 0.99,
            "illustrative": 0.72,
            "black_grey_realism": 0.58,
            "botanical": 0.48,
            "abstract": 0.44,
            "micro_realism": 0.28,
            "neo_traditional": 0.12,
            "engraving": 0.08,
        },
        "visual_traits": {
            "color": 0.74,
            "line_weight": 0.18,
            "density": 0.82,
            "contrast": 0.86,
            "realism": 0.96,
            "organic": 0.72,
            "geometric": 0.48,
            "symmetry": 0.72,
        },
        "motifs": [
            "cracked porcelain mask",
            "bioluminescent mushrooms",
            "mossy forest",
            "hidden inner world",
            "transformation",
            "dreamlike nature",
        ],
        "body_area": "front-side upper thigh",
        "skin_tone": "medium-light",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM026": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785781754/style_match/cards/SM026.jpg",
        "cloudinary_public_id": "style_match/cards/SM026",
        "primary_style": "black_grey_realism",
        "style_weights": {
            "black_grey_realism": 0.99,
            "geometric": 0.9,
            "micro_realism": 0.58,
            "illustrative": 0.46,
            "fine_line": 0.38,
            "dotwork": 0.3,
            "engraving": 0.22,
            "minimalism": 0.14,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.22,
            "density": 0.64,
            "contrast": 0.72,
            "realism": 0.94,
            "organic": 0.62,
            "geometric": 0.82,
            "symmetry": 0.46,
        },
        "motifs": [
            "marble hand",
            "faceted crystal",
            "offering gesture",
            "circular arcs",
            "value",
            "fragility",
        ],
        "body_area": "outer upper arm",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM027": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785781757/style_match/cards/SM027.jpg",
        "cloudinary_public_id": "style_match/cards/SM027",
        "primary_style": "japanese",
        "style_weights": {
            "japanese": 0.99,
            "illustrative": 0.78,
            "neo_traditional": 0.64,
            "american_traditional": 0.48,
            "blackwork": 0.42,
            "botanical": 0.24,
            "ornamental": 0.22,
            "color_realism": 0.18,
        },
        "visual_traits": {
            "color": 0.72,
            "line_weight": 0.7,
            "density": 0.84,
            "contrast": 0.78,
            "realism": 0.5,
            "organic": 0.96,
            "geometric": 0.18,
            "symmetry": 0.2,
        },
        "motifs": [
            "giant salamander",
            "river currents",
            "stylized waves",
            "reeds",
            "aquatic life",
            "resilience",
        ],
        "body_area": "inner calf",
        "skin_tone": "dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM028": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785783213/style_match/cards/SM028.jpg",
        "cloudinary_public_id": "style_match/cards/SM028",
        "primary_style": "ornamental",
        "style_weights": {
            "ornamental": 0.99,
            "blackwork": 0.78,
            "fine_line": 0.58,
            "dotwork": 0.42,
            "geometric": 0.38,
            "illustrative": 0.28,
            "botanical": 0.22,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.44,
            "density": 0.72,
            "contrast": 0.78,
            "realism": 0.08,
            "organic": 0.86,
            "geometric": 0.54,
            "symmetry": 0.99,
        },
        "motifs": [
            "seed-pod ornament",
            "winged flourish",
            "floral arabesque",
            "scrollwork",
            "symmetry",
            "lower-back crest",
        ],
        "body_area": "lower back",
        "skin_tone": "medium-dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM029": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785783216/style_match/cards/SM029.jpg",
        "cloudinary_public_id": "style_match/cards/SM029",
        "primary_style": "geometric",
        "style_weights": {
            "geometric": 0.99,
            "blackwork": 0.88,
            "fine_line": 0.64,
            "minimalism": 0.54,
            "illustrative": 0.38,
            "dotwork": 0.22,
            "cybersigilism": 0.18,
            "abstract": 0.16,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.3,
            "density": 0.66,
            "contrast": 0.76,
            "realism": 0.28,
            "organic": 0.06,
            "geometric": 0.99,
            "symmetry": 0.98,
        },
        "motifs": [
            "suspension bridge",
            "circular tunnel",
            "vanishing point",
            "eclipse",
            "architectural perspective",
            "concentric rings",
        ],
        "body_area": "upper back",
        "skin_tone": "light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM030": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785783219/style_match/cards/SM030.jpg",
        "cloudinary_public_id": "style_match/cards/SM030",
        "primary_style": "abstract",
        "style_weights": {
            "abstract": 0.99,
            "illustrative": 0.62,
            "minimalism": 0.54,
            "geometric": 0.48,
            "watercolor": 0.42,
            "cybersigilism": 0.22,
            "fine_line": 0.12,
            "color_realism": 0.08,
        },
        "visual_traits": {
            "color": 0.95,
            "line_weight": 0.05,
            "density": 0.34,
            "contrast": 0.52,
            "realism": 0.06,
            "organic": 0.72,
            "geometric": 0.58,
            "symmetry": 0.18,
        },
        "motifs": [
            "folded ribbons",
            "color cascade",
            "flowing helix",
            "overlapping bands",
            "motion",
            "transformation",
        ],
        "body_area": "sternum and upper abdomen",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM031": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785783221/style_match/cards/SM031.jpg",
        "cloudinary_public_id": "style_match/cards/SM031",
        "primary_style": "neo_traditional",
        "style_weights": {
            "neo_traditional": 0.99,
            "illustrative": 0.88,
            "american_traditional": 0.62,
            "japanese": 0.38,
            "ornamental": 0.34,
            "color_realism": 0.24,
            "blackwork": 0.22,
            "abstract": 0.16,
        },
        "visual_traits": {
            "color": 0.84,
            "line_weight": 0.74,
            "density": 0.78,
            "contrast": 0.82,
            "realism": 0.42,
            "organic": 0.88,
            "geometric": 0.24,
            "symmetry": 0.22,
        },
        "motifs": [
            "ornate teapot",
            "storm cloud",
            "lightning bolt",
            "pouring steam",
            "tempest",
            "magic",
        ],
        "body_area": "side ribcage",
        "skin_tone": "light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM032": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785783224/style_match/cards/SM032.jpg",
        "cloudinary_public_id": "style_match/cards/SM032",
        "primary_style": "dotwork",
        "style_weights": {
            "dotwork": 0.99,
            "engraving": 0.94,
            "black_grey_realism": 0.54,
            "illustrative": 0.52,
            "fine_line": 0.42,
            "geometric": 0.28,
            "botanical": 0.22,
            "minimalism": 0.08,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.16,
            "density": 0.88,
            "contrast": 0.66,
            "realism": 0.72,
            "organic": 0.84,
            "geometric": 0.52,
            "symmetry": 0.44,
        },
        "motifs": [
            "desert canyon",
            "natural stone arch",
            "river",
            "mesas",
            "sparse trees",
            "vast landscape",
        ],
        "body_area": "front shin",
        "skin_tone": "dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM033": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785784008/style_match/cards/SM033.jpg",
        "cloudinary_public_id": "style_match/cards/SM033",
        "primary_style": "botanical",
        "style_weights": {
            "botanical": 0.99,
            "fine_line": 0.76,
            "illustrative": 0.58,
            "engraving": 0.38,
            "dotwork": 0.32,
            "minimalism": 0.28,
            "color_realism": 0.22,
            "ornamental": 0.18,
        },
        "visual_traits": {
            "color": 0.42,
            "line_weight": 0.18,
            "density": 0.62,
            "contrast": 0.5,
            "realism": 0.68,
            "organic": 0.99,
            "geometric": 0.08,
            "symmetry": 0.22,
        },
        "motifs": [
            "unfurling fern",
            "fiddleheads",
            "fern fronds",
            "new growth",
            "forest",
            "renewal",
        ],
        "body_area": "outer shoulder and upper arm",
        "skin_tone": "medium-dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM034": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785784010/style_match/cards/SM034.jpg",
        "cloudinary_public_id": "style_match/cards/SM034",
        "primary_style": "cybersigilism",
        "style_weights": {
            "cybersigilism": 0.99,
            "ornamental": 0.78,
            "blackwork": 0.72,
            "abstract": 0.64,
            "geometric": 0.46,
            "fine_line": 0.38,
            "illustrative": 0.2,
            "minimalism": 0.14,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.54,
            "density": 0.58,
            "contrast": 0.88,
            "realism": 0.05,
            "organic": 0.62,
            "geometric": 0.82,
            "symmetry": 0.88,
        },
        "motifs": [
            "exoskeleton wings",
            "black spikes",
            "central spine",
            "negative space",
            "biomechanical lattice",
            "sharp curves",
        ],
        "body_area": "outer thigh",
        "skin_tone": "medium-light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM035": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785784014/style_match/cards/SM035.jpg",
        "cloudinary_public_id": "style_match/cards/SM035",
        "primary_style": "illustrative",
        "style_weights": {
            "illustrative": 0.99,
            "color_realism": 0.72,
            "micro_realism": 0.66,
            "neo_traditional": 0.34,
            "engraving": 0.32,
            "watercolor": 0.3,
            "abstract": 0.28,
            "fine_line": 0.22,
        },
        "visual_traits": {
            "color": 0.74,
            "line_weight": 0.2,
            "density": 0.76,
            "contrast": 0.62,
            "realism": 0.72,
            "organic": 0.92,
            "geometric": 0.3,
            "symmetry": 0.44,
        },
        "motifs": [
            "surreal seashell",
            "stone staircase",
            "flowing stream",
            "hidden doorway",
            "miniature landscape",
            "sanctuary",
        ],
        "body_area": "inner forearm",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM036": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785784018/style_match/cards/SM036.jpg",
        "cloudinary_public_id": "style_match/cards/SM036",
        "primary_style": "minimalism",
        "style_weights": {
            "minimalism": 0.99,
            "fine_line": 0.94,
            "botanical": 0.76,
            "ornamental": 0.46,
            "illustrative": 0.28,
            "geometric": 0.14,
            "abstract": 0.12,
            "dotwork": 0.08,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.05,
            "density": 0.08,
            "contrast": 0.28,
            "realism": 0.16,
            "organic": 0.96,
            "geometric": 0.1,
            "symmetry": 0.12,
        },
        "motifs": [
            "ginkgo leaves",
            "wind",
            "single flowing vine",
            "delicate stems",
            "movement",
            "simplicity",
        ],
        "body_area": "outer calf",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM037": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785784021/style_match/cards/SM037.jpg",
        "cloudinary_public_id": "style_match/cards/SM037",
        "primary_style": "american_traditional",
        "style_weights": {
            "american_traditional": 0.99,
            "botanical": 0.88,
            "neo_traditional": 0.72,
            "illustrative": 0.52,
            "blackwork": 0.42,
            "color_realism": 0.26,
            "japanese": 0.16,
            "ornamental": 0.14,
        },
        "visual_traits": {
            "color": 0.92,
            "line_weight": 0.84,
            "density": 0.74,
            "contrast": 0.9,
            "realism": 0.42,
            "organic": 0.96,
            "geometric": 0.16,
            "symmetry": 0.48,
        },
        "motifs": [
            "pomegranate fruit",
            "pomegranate blossom",
            "split fruit",
            "seeds",
            "branch",
            "abundance",
        ],
        "body_area": "outer forearm",
        "skin_tone": "light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM038": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785785921/style_match/cards/SM038.jpg",
        "cloudinary_public_id": "style_match/cards/SM038",
        "primary_style": "engraving",
        "style_weights": {
            "engraving": 0.99,
            "illustrative": 0.82,
            "black_grey_realism": 0.6,
            "dotwork": 0.48,
            "abstract": 0.44,
            "fine_line": 0.38,
            "japanese": 0.22,
            "blackwork": 0.18,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.16,
            "density": 0.86,
            "contrast": 0.7,
            "realism": 0.72,
            "organic": 0.9,
            "geometric": 0.18,
            "symmetry": 0.22,
        },
        "motifs": [
            "surreal female portrait",
            "ocean waves",
            "sea cliffs",
            "cloud plateau",
            "profile",
            "merging landscape",
        ],
        "body_area": "shoulder blade",
        "skin_tone": "medium-dark",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM039": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785785924/style_match/cards/SM039.jpg",
        "cloudinary_public_id": "style_match/cards/SM039",
        "primary_style": "micro_realism",
        "style_weights": {
            "micro_realism": 0.99,
            "watercolor": 0.84,
            "color_realism": 0.78,
            "illustrative": 0.52,
            "minimalism": 0.4,
            "fine_line": 0.36,
            "black_grey_realism": 0.24,
            "abstract": 0.2,
        },
        "visual_traits": {
            "color": 0.58,
            "line_weight": 0.12,
            "density": 0.34,
            "contrast": 0.56,
            "realism": 0.88,
            "organic": 0.74,
            "geometric": 0.44,
            "symmetry": 0.62,
        },
        "motifs": [
            "glass bottle",
            "storm cloud",
            "rain",
            "trapped weather",
            "watercolor puddle",
            "melancholy",
        ],
        "body_area": "inner upper arm",
        "skin_tone": "medium-light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM040": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785785927/style_match/cards/SM040.jpg",
        "cloudinary_public_id": "style_match/cards/SM040",
        "primary_style": "fine_line",
        "style_weights": {
            "fine_line": 0.99,
            "minimalism": 0.86,
            "illustrative": 0.56,
            "geometric": 0.44,
            "dotwork": 0.24,
            "engraving": 0.18,
            "botanical": 0.12,
            "blackwork": 0.1,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.05,
            "density": 0.16,
            "contrast": 0.34,
            "realism": 0.58,
            "organic": 0.9,
            "geometric": 0.46,
            "symmetry": 0.98,
        },
        "motifs": [
            "luna moth",
            "feathered antennae",
            "long wing tails",
            "wing markings",
            "metamorphosis",
            "night",
        ],
        "body_area": "inner ankle",
        "skin_tone": "medium",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM041": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785785931/style_match/cards/SM041.jpg",
        "cloudinary_public_id": "style_match/cards/SM041",
        "primary_style": "japanese",
        "style_weights": {
            "japanese": 0.99,
            "illustrative": 0.82,
            "blackwork": 0.7,
            "neo_traditional": 0.58,
            "botanical": 0.38,
            "american_traditional": 0.34,
            "engraving": 0.3,
            "dotwork": 0.2,
        },
        "visual_traits": {
            "color": 0.22,
            "line_weight": 0.62,
            "density": 0.92,
            "contrast": 0.82,
            "realism": 0.6,
            "organic": 0.98,
            "geometric": 0.18,
            "symmetry": 0.28,
        },
        "motifs": [
            "red-crowned crane",
            "pine tree",
            "storm clouds",
            "wind",
            "flight",
            "longevity",
        ],
        "body_area": "upper and mid-back",
        "skin_tone": "medium-dark",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM042": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785785935/style_match/cards/SM042.jpg",
        "cloudinary_public_id": "style_match/cards/SM042",
        "primary_style": "dotwork",
        "style_weights": {
            "dotwork": 0.99,
            "geometric": 0.94,
            "blackwork": 0.72,
            "abstract": 0.58,
            "minimalism": 0.34,
            "engraving": 0.28,
            "fine_line": 0.24,
            "cybersigilism": 0.18,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.14,
            "density": 0.72,
            "contrast": 0.78,
            "realism": 0.06,
            "organic": 0.34,
            "geometric": 0.99,
            "symmetry": 0.98,
        },
        "motifs": [
            "meteorite impact crater",
            "concentric rings",
            "fractured earth",
            "stippled dust",
            "central void",
            "shockwave",
        ],
        "body_area": "outer thigh",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM043": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786553/style_match/cards/SM043.jpg",
        "cloudinary_public_id": "style_match/cards/SM043",
        "primary_style": "color_realism",
        "style_weights": {
            "color_realism": 0.99,
            "illustrative": 0.68,
            "micro_realism": 0.6,
            "neo_traditional": 0.44,
            "watercolor": 0.22,
            "black_grey_realism": 0.18,
            "american_traditional": 0.16,
            "botanical": 0.12,
        },
        "visual_traits": {
            "color": 0.82,
            "line_weight": 0.22,
            "density": 0.62,
            "contrast": 0.76,
            "realism": 0.96,
            "organic": 0.95,
            "geometric": 0.08,
            "symmetry": 0.58,
        },
        "motifs": [
            "puffin",
            "seaweed",
            "coastal rock",
            "seabird",
            "red beak",
            "shoreline",
        ],
        "body_area": "outer upper arm",
        "skin_tone": "dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM044": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786556/style_match/cards/SM044.jpg",
        "cloudinary_public_id": "style_match/cards/SM044",
        "primary_style": "illustrative",
        "style_weights": {
            "illustrative": 0.99,
            "blackwork": 0.88,
            "engraving": 0.76,
            "dotwork": 0.54,
            "black_grey_realism": 0.44,
            "abstract": 0.42,
            "geometric": 0.28,
            "fine_line": 0.22,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.52,
            "density": 0.74,
            "contrast": 0.9,
            "realism": 0.55,
            "organic": 0.62,
            "geometric": 0.54,
            "symmetry": 0.98,
        },
        "motifs": [
            "lighthouse beetle",
            "insect anatomy",
            "lighthouse tower",
            "beacon",
            "surreal hybrid",
            "coastal navigation",
        ],
        "body_area": "side torso",
        "skin_tone": "light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM045": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786558/style_match/cards/SM045.jpg",
        "cloudinary_public_id": "style_match/cards/SM045",
        "primary_style": "blackwork",
        "style_weights": {
            "blackwork": 0.99,
            "geometric": 0.94,
            "minimalism": 0.82,
            "abstract": 0.74,
            "cybersigilism": 0.42,
            "fine_line": 0.18,
            "ornamental": 0.12,
            "dotwork": 0.1,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.95,
            "density": 0.58,
            "contrast": 0.99,
            "realism": 0.03,
            "organic": 0.02,
            "geometric": 0.99,
            "symmetry": 0.86,
        },
        "motifs": [
            "brutalist archway",
            "impossible shadow",
            "portal",
            "zigzag path",
            "negative space",
            "monolith",
        ],
        "body_area": "inner forearm",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM046": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786561/style_match/cards/SM046.jpg",
        "cloudinary_public_id": "style_match/cards/SM046",
        "primary_style": "neo_traditional",
        "style_weights": {
            "neo_traditional": 0.99,
            "illustrative": 0.9,
            "blackwork": 0.72,
            "color_realism": 0.54,
            "american_traditional": 0.48,
            "japanese": 0.4,
            "engraving": 0.2,
            "dotwork": 0.14,
        },
        "visual_traits": {
            "color": 0.88,
            "line_weight": 0.82,
            "density": 0.9,
            "contrast": 0.96,
            "realism": 0.62,
            "organic": 0.98,
            "geometric": 0.08,
            "symmetry": 0.28,
        },
        "motifs": [
            "deep-sea anglerfish",
            "bioluminescent lure",
            "fangs",
            "flowing fins",
            "abyss",
            "predator",
        ],
        "body_area": "outer calf",
        "skin_tone": "medium-dark",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM047": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786565/style_match/cards/SM047.jpg",
        "cloudinary_public_id": "style_match/cards/SM047",
        "primary_style": "geometric",
        "style_weights": {
            "geometric": 0.99,
            "botanical": 0.92,
            "dotwork": 0.7,
            "blackwork": 0.62,
            "ornamental": 0.56,
            "illustrative": 0.38,
            "fine_line": 0.34,
            "minimalism": 0.16,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.3,
            "density": 0.84,
            "contrast": 0.8,
            "realism": 0.26,
            "organic": 0.84,
            "geometric": 0.99,
            "symmetry": 0.99,
        },
        "motifs": [
            "faceted dahlia",
            "layered petals",
            "flower stem",
            "leaves",
            "radial geometry",
            "crystal facets",
        ],
        "body_area": "shoulder blade",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM048": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786712/style_match/cards/SM048.jpg",
        "cloudinary_public_id": "style_match/cards/SM048",
        "primary_style": "watercolor",
        "style_weights": {
            "watercolor": 0.99,
            "abstract": 0.76,
            "color_realism": 0.66,
            "illustrative": 0.58,
            "micro_realism": 0.38,
            "botanical": 0.12,
            "black_grey_realism": 0.08,
            "fine_line": 0.06,
        },
        "visual_traits": {
            "color": 0.96,
            "line_weight": 0.06,
            "density": 0.5,
            "contrast": 0.6,
            "realism": 0.54,
            "organic": 0.94,
            "geometric": 0.1,
            "symmetry": 0.3,
        },
        "motifs": [
            "desert thunderstorm",
            "storm clouds",
            "rain shaft",
            "canyon mesas",
            "desert basin",
            "reflected color",
        ],
        "body_area": "front shin",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM049": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786715/style_match/cards/SM049.jpg",
        "cloudinary_public_id": "style_match/cards/SM049",
        "primary_style": "minimalism",
        "style_weights": {
            "minimalism": 0.99,
            "fine_line": 0.94,
            "illustrative": 0.54,
            "abstract": 0.46,
            "japanese": 0.24,
            "engraving": 0.18,
            "blackwork": 0.12,
            "geometric": 0.1,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.05,
            "density": 0.1,
            "contrast": 0.24,
            "realism": 0.28,
            "organic": 0.88,
            "geometric": 0.2,
            "symmetry": 0.3,
        },
        "motifs": [
            "matchstick",
            "smoke",
            "ocean wave",
            "transformation",
            "single line",
            "fleeting moment",
        ],
        "body_area": "upper chest",
        "skin_tone": "dark",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM050": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786717/style_match/cards/SM050.jpg",
        "cloudinary_public_id": "style_match/cards/SM050",
        "primary_style": "cybersigilism",
        "style_weights": {
            "cybersigilism": 0.99,
            "ornamental": 0.88,
            "geometric": 0.8,
            "blackwork": 0.72,
            "abstract": 0.68,
            "illustrative": 0.46,
            "color_realism": 0.2,
            "dotwork": 0.18,
        },
        "visual_traits": {
            "color": 0.44,
            "line_weight": 0.62,
            "density": 0.78,
            "contrast": 0.88,
            "realism": 0.14,
            "organic": 0.72,
            "geometric": 0.92,
            "symmetry": 0.99,
        },
        "motifs": [
            "manta ray",
            "techno-organic wings",
            "tribal circuitry",
            "violet accents",
            "symmetrical crest",
            "ocean flight",
        ],
        "body_area": "lower back",
        "skin_tone": "light",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM051": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786720/style_match/cards/SM051.jpg",
        "cloudinary_public_id": "style_match/cards/SM051",
        "primary_style": "black_grey_realism",
        "style_weights": {
            "black_grey_realism": 0.99,
            "engraving": 0.64,
            "illustrative": 0.58,
            "dotwork": 0.52,
            "micro_realism": 0.46,
            "botanical": 0.42,
            "fine_line": 0.32,
            "blackwork": 0.18,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.2,
            "density": 0.78,
            "contrast": 0.72,
            "realism": 0.99,
            "organic": 0.98,
            "geometric": 0.04,
            "symmetry": 0.34,
        },
        "motifs": [
            "mountain hare",
            "winter grass",
            "wild rabbit",
            "fur texture",
            "alert ears",
            "woodland",
        ],
        "body_area": "outer shoulder and upper arm",
        "skin_tone": "medium",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM052": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785786723/style_match/cards/SM052.jpg",
        "cloudinary_public_id": "style_match/cards/SM052",
        "primary_style": "botanical",
        "style_weights": {
            "botanical": 0.99,
            "watercolor": 0.92,
            "illustrative": 0.56,
            "color_realism": 0.42,
            "abstract": 0.36,
            "fine_line": 0.28,
            "ornamental": 0.18,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.68,
            "line_weight": 0.12,
            "density": 0.64,
            "contrast": 0.54,
            "realism": 0.46,
            "organic": 0.99,
            "geometric": 0.06,
            "symmetry": 0.24,
        },
        "motifs": [
            "giant kelp",
            "sea lettuce",
            "marine leaves",
            "underwater garden",
            "green fronds",
            "ocean flora",
        ],
        "body_area": "outer forearm",
        "skin_tone": "medium-dark",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM053": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785788537/style_match/cards/SM053.jpg",
        "cloudinary_public_id": "style_match/cards/SM053",
        "primary_style": "ornamental",
        "style_weights": {
            "ornamental": 0.99,
            "fine_line": 0.84,
            "illustrative": 0.78,
            "dotwork": 0.52,
            "blackwork": 0.44,
            "geometric": 0.38,
            "engraving": 0.3,
            "minimalism": 0.16,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.18,
            "density": 0.72,
            "contrast": 0.58,
            "realism": 0.3,
            "organic": 0.99,
            "geometric": 0.46,
            "symmetry": 0.97,
        },
        "motifs": [
            "ornamental jellyfish",
            "scalloped bell",
            "filigree",
            "curling tentacles",
            "teardrop ornaments",
            "ocean life",
        ],
        "body_area": "outer thigh",
        "skin_tone": "dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM054": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785788554/style_match/cards/SM054.jpg",
        "cloudinary_public_id": "style_match/cards/SM054",
        "primary_style": "abstract",
        "style_weights": {
            "abstract": 0.99,
            "blackwork": 0.96,
            "illustrative": 0.44,
            "black_grey_realism": 0.36,
            "engraving": 0.32,
            "japanese": 0.28,
            "minimalism": 0.24,
            "cybersigilism": 0.16,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.72,
            "density": 0.68,
            "contrast": 0.96,
            "realism": 0.22,
            "organic": 0.98,
            "geometric": 0.06,
            "symmetry": 0.12,
        },
        "motifs": [
            "eroded basalt",
            "river channels",
            "geological strata",
            "aerial landscape",
            "negative-space streams",
            "erosion",
        ],
        "body_area": "side torso",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM055": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785788556/style_match/cards/SM055.jpg",
        "cloudinary_public_id": "style_match/cards/SM055",
        "primary_style": "american_traditional",
        "style_weights": {
            "american_traditional": 0.99,
            "illustrative": 0.86,
            "neo_traditional": 0.62,
            "blackwork": 0.44,
            "color_realism": 0.28,
            "engraving": 0.18,
            "botanical": 0.16,
            "japanese": 0.12,
        },
        "visual_traits": {
            "color": 0.86,
            "line_weight": 0.88,
            "density": 0.82,
            "contrast": 0.94,
            "realism": 0.5,
            "organic": 0.72,
            "geometric": 0.46,
            "symmetry": 0.26,
        },
        "motifs": [
            "covered bridge",
            "river",
            "pine trees",
            "stone abutments",
            "woodland",
            "rural architecture",
        ],
        "body_area": "shoulder blade",
        "skin_tone": "light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM056": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785788560/style_match/cards/SM056.jpg",
        "cloudinary_public_id": "style_match/cards/SM056",
        "primary_style": "micro_realism",
        "style_weights": {
            "micro_realism": 0.99,
            "color_realism": 0.84,
            "geometric": 0.74,
            "minimalism": 0.58,
            "illustrative": 0.38,
            "fine_line": 0.34,
            "abstract": 0.22,
            "black_grey_realism": 0.16,
        },
        "visual_traits": {
            "color": 0.68,
            "line_weight": 0.16,
            "density": 0.48,
            "contrast": 0.58,
            "realism": 0.94,
            "organic": 0.56,
            "geometric": 0.96,
            "symmetry": 0.94,
        },
        "motifs": [
            "desert doorway",
            "sunset",
            "mesas",
            "winding trail",
            "rectangular frame",
            "horizon",
        ],
        "body_area": "inner ankle",
        "skin_tone": "medium-light",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM057": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785788562/style_match/cards/SM057.jpg",
        "cloudinary_public_id": "style_match/cards/SM057",
        "primary_style": "dotwork",
        "style_weights": {
            "dotwork": 0.99,
            "abstract": 0.74,
            "color_realism": 0.64,
            "illustrative": 0.58,
            "geometric": 0.54,
            "micro_realism": 0.44,
            "watercolor": 0.38,
            "blackwork": 0.18,
        },
        "visual_traits": {
            "color": 0.66,
            "line_weight": 0.03,
            "density": 0.78,
            "contrast": 0.68,
            "realism": 0.5,
            "organic": 0.94,
            "geometric": 0.7,
            "symmetry": 0.62,
        },
        "motifs": [
            "spiral galaxy",
            "nebula",
            "galactic core",
            "star field",
            "cosmic dust",
            "deep space",
        ],
        "body_area": "back of upper arm",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM058": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785788565/style_match/cards/SM058.jpg",
        "cloudinary_public_id": "style_match/cards/SM058",
        "primary_style": "engraving",
        "style_weights": {
            "engraving": 0.99,
            "botanical": 0.94,
            "illustrative": 0.82,
            "fine_line": 0.62,
            "blackwork": 0.5,
            "black_grey_realism": 0.34,
            "dotwork": 0.22,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.18,
            "density": 0.8,
            "contrast": 0.62,
            "realism": 0.72,
            "organic": 0.99,
            "geometric": 0.22,
            "symmetry": 0.58,
        },
        "motifs": [
            "artichoke",
            "layered bracts",
            "serrated leaves",
            "cut stem",
            "botanical study",
            "cross-hatching",
        ],
        "body_area": "inner calf",
        "skin_tone": "medium-dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM059": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785790680/style_match/cards/SM059.jpg",
        "cloudinary_public_id": "style_match/cards/SM059",
        "primary_style": "color_realism",
        "style_weights": {
            "color_realism": 0.99,
            "illustrative": 0.84,
            "abstract": 0.52,
            "neo_traditional": 0.5,
            "micro_realism": 0.46,
            "fine_line": 0.24,
            "watercolor": 0.18,
            "botanical": 0.12,
        },
        "visual_traits": {
            "color": 0.84,
            "line_weight": 0.22,
            "density": 0.68,
            "contrast": 0.72,
            "realism": 0.82,
            "organic": 0.99,
            "geometric": 0.08,
            "symmetry": 0.18,
        },
        "motifs": [
            "panther chameleon",
            "curled tail",
            "color ribbons",
            "reptile scales",
            "green camouflage",
            "transformation",
        ],
        "body_area": "outer forearm",
        "skin_tone": "dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM060": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785790683/style_match/cards/SM060.jpg",
        "cloudinary_public_id": "style_match/cards/SM060",
        "primary_style": "black_grey_realism",
        "style_weights": {
            "black_grey_realism": 0.99,
            "micro_realism": 0.64,
            "illustrative": 0.42,
            "engraving": 0.3,
            "fine_line": 0.22,
            "blackwork": 0.16,
            "neo_traditional": 0.1,
            "abstract": 0.06,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.08,
            "density": 0.86,
            "contrast": 0.76,
            "realism": 0.99,
            "organic": 0.98,
            "geometric": 0.02,
            "symmetry": 0.4,
        },
        "motifs": [
            "elderly woman",
            "windswept hair",
            "closed eyes",
            "upward gaze",
            "aging",
            "portrait",
        ],
        "body_area": "outer upper thigh",
        "skin_tone": "light",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM061": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785790686/style_match/cards/SM061.jpg",
        "cloudinary_public_id": "style_match/cards/SM061",
        "primary_style": "blackwork",
        "style_weights": {
            "blackwork": 0.99,
            "black_grey_realism": 0.86,
            "illustrative": 0.66,
            "ornamental": 0.52,
            "engraving": 0.46,
            "neo_traditional": 0.2,
            "dotwork": 0.16,
            "japanese": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.54,
            "density": 0.82,
            "contrast": 0.9,
            "realism": 0.86,
            "organic": 0.99,
            "geometric": 0.12,
            "symmetry": 0.32,
        },
        "motifs": [
            "coiled snake",
            "black scales",
            "serpentine body",
            "forked tongue",
            "ornamental curls",
            "spine",
        ],
        "body_area": "upper and mid-back",
        "skin_tone": "medium-light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM062": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785788569/style_match/cards/SM062.jpg",
        "cloudinary_public_id": "style_match/cards/SM062",
        "primary_style": "color_realism",
        "style_weights": {
            "color_realism": 0.99,
            "micro_realism": 0.92,
            "abstract": 0.64,
            "watercolor": 0.58,
            "illustrative": 0.54,
            "botanical": 0.46,
            "black_grey_realism": 0.2,
            "geometric": 0.14,
        },
        "visual_traits": {
            "color": 0.98,
            "line_weight": 0.04,
            "density": 0.72,
            "contrast": 0.84,
            "realism": 0.98,
            "organic": 0.88,
            "geometric": 0.56,
            "symmetry": 0.72,
        },
        "motifs": [
            "glass marble",
            "autumn forest",
            "refracted light",
            "rainbow prism",
            "trees",
            "miniature landscape",
        ],
        "body_area": "upper chest",
        "skin_tone": "light",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM063": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785797734/style_match/cards/SM063.jpg",
        "cloudinary_public_id": "style_match/cards/SM063",
        "primary_style": "japanese",
        "style_weights": {
            "japanese": 0.99,
            "blackwork": 0.86,
            "engraving": 0.72,
            "illustrative": 0.64,
            "dotwork": 0.34,
            "ornamental": 0.28,
            "black_grey_realism": 0.22,
            "neo_traditional": 0.16,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.54,
            "density": 0.84,
            "contrast": 0.86,
            "realism": 0.58,
            "organic": 0.72,
            "geometric": 0.46,
            "symmetry": 0.78,
        },
        "motifs": [
            "temple bell",
            "torii gate",
            "wind bars",
            "storm clouds",
            "maple leaves",
            "autumn",
        ],
        "body_area": "upper and mid-back",
        "skin_tone": "dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM064": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785797737/style_match/cards/SM064.jpg",
        "cloudinary_public_id": "style_match/cards/SM064",
        "primary_style": "neo_traditional",
        "style_weights": {
            "neo_traditional": 0.99,
            "geometric": 0.88,
            "illustrative": 0.84,
            "color_realism": 0.64,
            "blackwork": 0.52,
            "abstract": 0.48,
            "engraving": 0.24,
            "japanese": 0.12,
        },
        "visual_traits": {
            "color": 0.68,
            "line_weight": 0.58,
            "density": 0.86,
            "contrast": 0.82,
            "realism": 0.68,
            "organic": 0.78,
            "geometric": 0.86,
            "symmetry": 0.56,
        },
        "motifs": [
            "mountain goat",
            "faceted horns",
            "angular mane",
            "ibex portrait",
            "gemstone facets",
            "alpine wildlife",
        ],
        "body_area": "outer thigh",
        "skin_tone": "medium-dark",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM065": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785797740/style_match/cards/SM065.jpg",
        "cloudinary_public_id": "style_match/cards/SM065",
        "primary_style": "fine_line",
        "style_weights": {
            "fine_line": 0.99,
            "minimalism": 0.9,
            "illustrative": 0.62,
            "engraving": 0.46,
            "dotwork": 0.24,
            "black_grey_realism": 0.22,
            "ornamental": 0.18,
            "blackwork": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.04,
            "density": 0.22,
            "contrast": 0.24,
            "realism": 0.7,
            "organic": 0.99,
            "geometric": 0.04,
            "symmetry": 0.24,
        },
        "motifs": [
            "drifting octopus",
            "slender tentacles",
            "suction cups",
            "cephalopod",
            "floating",
            "marine life",
        ],
        "body_area": "inner forearm",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM066": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785797742/style_match/cards/SM066.jpg",
        "cloudinary_public_id": "style_match/cards/SM066",
        "primary_style": "illustrative",
        "style_weights": {
            "illustrative": 0.99,
            "color_realism": 0.84,
            "abstract": 0.72,
            "neo_traditional": 0.56,
            "watercolor": 0.52,
            "engraving": 0.38,
            "micro_realism": 0.34,
            "botanical": 0.12,
        },
        "visual_traits": {
            "color": 0.88,
            "line_weight": 0.32,
            "density": 0.76,
            "contrast": 0.72,
            "realism": 0.78,
            "organic": 0.99,
            "geometric": 0.12,
            "symmetry": 0.18,
        },
        "motifs": [
            "panther chameleon",
            "bare twig",
            "curled tail",
            "mosaic scales",
            "color blocks",
            "camouflage",
        ],
        "body_area": "shoulder blade",
        "skin_tone": "medium-light",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM067": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785797747/style_match/cards/SM067.jpg",
        "cloudinary_public_id": "style_match/cards/SM067",
        "primary_style": "blackwork",
        "style_weights": {
            "blackwork": 0.99,
            "botanical": 0.92,
            "illustrative": 0.72,
            "engraving": 0.42,
            "abstract": 0.34,
            "fine_line": 0.3,
            "japanese": 0.22,
            "neo_traditional": 0.14,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.72,
            "density": 0.58,
            "contrast": 0.99,
            "realism": 0.44,
            "organic": 0.99,
            "geometric": 0.06,
            "symmetry": 0.36,
        },
        "motifs": [
            "wind-torn iris",
            "ragged petals",
            "sword leaves",
            "solid black petals",
            "negative-space veins",
            "flower",
        ],
        "body_area": "outer upper arm",
        "skin_tone": "light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM068": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785798466/style_match/cards/SM068.jpg",
        "cloudinary_public_id": "style_match/cards/SM068",
        "primary_style": "watercolor",
        "style_weights": {
            "watercolor": 0.99,
            "abstract": 0.88,
            "illustrative": 0.72,
            "color_realism": 0.52,
            "minimalism": 0.42,
            "micro_realism": 0.28,
            "fine_line": 0.18,
            "black_grey_realism": 0.08,
        },
        "visual_traits": {
            "color": 0.82,
            "line_weight": 0.08,
            "density": 0.58,
            "contrast": 0.62,
            "realism": 0.32,
            "organic": 0.94,
            "geometric": 0.06,
            "symmetry": 0.24,
        },
        "motifs": [
            "solitary figure",
            "rain cloud",
            "dripping rain",
            "reflection",
            "storm",
            "solitude",
        ],
        "body_area": "side torso",
        "skin_tone": "dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM069": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785798469/style_match/cards/SM069.jpg",
        "cloudinary_public_id": "style_match/cards/SM069",
        "primary_style": "minimalism",
        "style_weights": {
            "minimalism": 0.99,
            "fine_line": 0.92,
            "dotwork": 0.76,
            "geometric": 0.52,
            "illustrative": 0.34,
            "blackwork": 0.18,
            "engraving": 0.16,
            "micro_realism": 0.12,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.03,
            "density": 0.12,
            "contrast": 0.24,
            "realism": 0.42,
            "organic": 0.58,
            "geometric": 0.72,
            "symmetry": 0.48,
        },
        "motifs": [
            "mountain peaks",
            "drifting cloud",
            "horizon line",
            "distant range",
            "mist",
            "tiny landscape",
        ],
        "body_area": "outer ankle",
        "skin_tone": "medium-dark",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM070": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785798472/style_match/cards/SM070.jpg",
        "cloudinary_public_id": "style_match/cards/SM070",
        "primary_style": "cybersigilism",
        "style_weights": {
            "cybersigilism": 0.99,
            "blackwork": 0.88,
            "ornamental": 0.82,
            "geometric": 0.78,
            "illustrative": 0.62,
            "engraving": 0.46,
            "dotwork": 0.28,
            "abstract": 0.22,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.42,
            "density": 0.78,
            "contrast": 0.86,
            "realism": 0.52,
            "organic": 0.86,
            "geometric": 0.92,
            "symmetry": 0.96,
        },
        "motifs": [
            "scorpion",
            "segmented armor",
            "curved stinger",
            "gothic pincers",
            "techno-organic carapace",
            "arachnid",
        ],
        "body_area": "outer calf",
        "skin_tone": "medium",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM071": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785798476/style_match/cards/SM071.jpg",
        "cloudinary_public_id": "style_match/cards/SM071",
        "primary_style": "black_grey_realism",
        "style_weights": {
            "black_grey_realism": 0.99,
            "engraving": 0.78,
            "illustrative": 0.64,
            "micro_realism": 0.58,
            "fine_line": 0.42,
            "dotwork": 0.34,
            "minimalism": 0.22,
            "blackwork": 0.14,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.12,
            "density": 0.62,
            "contrast": 0.58,
            "realism": 0.96,
            "organic": 0.88,
            "geometric": 0.16,
            "symmetry": 0.28,
        },
        "motifs": [
            "empty rowboat",
            "misty lake",
            "reeds",
            "still water",
            "wooden hull",
            "solitude",
        ],
        "body_area": "lower back",
        "skin_tone": "light",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
    "SM072": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785798478/style_match/cards/SM072.jpg",
        "cloudinary_public_id": "style_match/cards/SM072",
        "primary_style": "ornamental",
        "style_weights": {
            "ornamental": 0.99,
            "watercolor": 0.9,
            "illustrative": 0.82,
            "fine_line": 0.68,
            "neo_traditional": 0.42,
            "color_realism": 0.34,
            "botanical": 0.28,
            "abstract": 0.24,
        },
        "visual_traits": {
            "color": 0.82,
            "line_weight": 0.2,
            "density": 0.7,
            "contrast": 0.68,
            "realism": 0.46,
            "organic": 0.99,
            "geometric": 0.2,
            "symmetry": 0.42,
        },
        "motifs": [
            "seahorse",
            "curling tail",
            "filigree",
            "watercolor splashes",
            "ocean life",
            "scrollwork",
        ],
        "body_area": "inner upper arm",
        "skin_tone": "medium-light",
        "quality_score": 0.99,
        "is_active": True,
        "is_approved": True,
    },
}


def seed_card_library(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    for card_id, defaults in CARDS.items():
        TattooCard.objects.update_or_create(card_id=card_id, defaults=defaults)


def remove_card_library(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    TattooCard.objects.filter(card_id__in=CARDS).delete()


class Migration(migrations.Migration):
    dependencies = [("style_match", "0003_seed_sm002")]

    operations = [migrations.RunPython(seed_card_library, remove_card_library)]
