from django.db import migrations


CARDS = {
    "SM106": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785852873/style_match/cards/SM106.jpg",
        "cloudinary_public_id": "style_match/cards/SM106",
        "primary_style": "geometric",
        "style_weights": {
            "geometric": 0.98,
            "minimalism": 0.72,
            "abstract": 0.68,
            "dotwork": 0.45,
            "blackwork": 0.38,
            "fine_line": 0.28,
            "illustrative": 0.18,
            "ornamental": 0.08,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.42,
            "density": 0.72,
            "contrast": 0.72,
            "realism": 0.02,
            "organic": 0.03,
            "geometric": 0.99,
            "symmetry": 0.16,
        },
        "motifs": [
            "aperiodic monotile tessellation",
            "einstein tile",
            "interlocking arrows",
            "missing central tile",
            "detached edge pieces",
            "mathematical tiling",
            "negative space",
        ],
        "body_area": "proximal forearm below elbow",
        "skin_tone": "dark",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM107": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785852876/style_match/cards/SM107.jpg",
        "cloudinary_public_id": "style_match/cards/SM107",
        "primary_style": "abstract",
        "style_weights": {
            "abstract": 0.96,
            "geometric": 0.86,
            "minimalism": 0.58,
            "dotwork": 0.48,
            "illustrative": 0.40,
            "fine_line": 0.32,
            "ornamental": 0.20,
            "engraving": 0.18,
        },
        "visual_traits": {
            "color": 0.16,
            "line_weight": 0.28,
            "density": 0.42,
            "contrast": 0.40,
            "realism": 0.18,
            "organic": 0.10,
            "geometric": 0.88,
            "symmetry": 0.72,
        },
        "motifs": [
            "separated ceramic shards",
            "amphora silhouette",
            "negative-space vessel",
            "broken pottery",
            "painted bands",
            "archaeological fragments",
            "reconstruction",
        ],
        "body_area": "outer upper arm",
        "skin_tone": "medium-light",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM108": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785852879/style_match/cards/SM108.jpg",
        "cloudinary_public_id": "style_match/cards/SM108",
        "primary_style": "neo_traditional",
        "style_weights": {
            "neo_traditional": 0.98,
            "ornamental": 0.90,
            "illustrative": 0.78,
            "color_realism": 0.58,
            "american_traditional": 0.48,
            "engraving": 0.36,
            "geometric": 0.32,
            "blackwork": 0.18,
        },
        "visual_traits": {
            "color": 0.76,
            "line_weight": 0.72,
            "density": 0.92,
            "contrast": 0.78,
            "realism": 0.58,
            "organic": 0.16,
            "geometric": 0.80,
            "symmetry": 0.88,
        },
        "motifs": [
            "mythic Sampo mill",
            "hand crank",
            "grain chamber",
            "salt crystals",
            "coin chamber",
            "ornate machine",
            "mythic artifact",
            "abundance",
        ],
        "body_area": "outer calf",
        "skin_tone": "medium-dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM109": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785852883/style_match/cards/SM109.jpg",
        "cloudinary_public_id": "style_match/cards/SM109",
        "primary_style": "ornamental",
        "style_weights": {
            "ornamental": 0.97,
            "fine_line": 0.78,
            "dotwork": 0.70,
            "illustrative": 0.60,
            "neo_traditional": 0.38,
            "engraving": 0.34,
            "geometric": 0.30,
            "minimalism": 0.10,
        },
        "visual_traits": {
            "color": 0.16,
            "line_weight": 0.30,
            "density": 0.82,
            "contrast": 0.48,
            "realism": 0.42,
            "organic": 0.82,
            "geometric": 0.54,
            "symmetry": 0.52,
        },
        "motifs": [
            "broken carved hair comb",
            "uneven teeth",
            "paisley filigree",
            "suspended ceramic beads",
            "hair ornament",
            "dangling chains",
            "weathered wood",
            "decorative carving",
        ],
        "body_area": "shoulder blade",
        "skin_tone": "light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM110": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785852886/style_match/cards/SM110.jpg",
        "cloudinary_public_id": "style_match/cards/SM110",
        "primary_style": "american_traditional",
        "style_weights": {
            "american_traditional": 0.98,
            "neo_traditional": 0.88,
            "illustrative": 0.68,
            "color_realism": 0.42,
            "botanical": 0.36,
            "engraving": 0.20,
            "blackwork": 0.18,
            "ornamental": 0.12,
        },
        "visual_traits": {
            "color": 0.86,
            "line_weight": 0.88,
            "density": 0.80,
            "contrast": 0.86,
            "realism": 0.48,
            "organic": 0.54,
            "geometric": 0.30,
            "symmetry": 0.18,
        },
        "motifs": [
            "carpenter hand plane",
            "timber block",
            "curled wood shaving",
            "red flower",
            "woodworking",
            "carpentry tool",
            "wood grain",
            "craftsmanship",
        ],
        "body_area": "front shoulder and upper arm",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
}


def seed_sm106_sm110(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    for card_id, defaults in CARDS.items():
        TattooCard.objects.update_or_create(card_id=card_id, defaults=defaults)


def remove_sm106_sm110(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    TattooCard.objects.filter(card_id__in=CARDS).delete()


class Migration(migrations.Migration):
    dependencies = [("style_match", "0005_seed_sm101_sm105")]

    operations = [migrations.RunPython(seed_sm106_sm110, remove_sm106_sm110)]
