from django.db import migrations


CARDS = {
    "SM111": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785859486/style_match/cards/SM111.jpg",
        "cloudinary_public_id": "style_match/cards/SM111",
        "primary_style": "black_grey_realism",
        "style_weights": {
            "black_grey_realism": 0.97,
            "dotwork": 0.82,
            "engraving": 0.74,
            "micro_realism": 0.68,
            "illustrative": 0.52,
            "blackwork": 0.46,
            "geometric": 0.18,
            "fine_line": 0.14,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.34,
            "density": 0.82,
            "contrast": 0.68,
            "realism": 0.92,
            "organic": 0.86,
            "geometric": 0.12,
            "symmetry": 0.18,
        },
        "motifs": [
            "Hallucigenia fossil",
            "Burgess shale",
            "fossil impression",
            "fractured stone slab",
            "radiating spines",
            "Cambrian organism",
            "paleontology",
            "geological specimen",
        ],
        "body_area": "outer thigh",
        "skin_tone": "dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM112": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785859494/style_match/cards/SM112.jpg",
        "cloudinary_public_id": "style_match/cards/SM112",
        "primary_style": "blackwork",
        "style_weights": {
            "blackwork": 0.96,
            "engraving": 0.90,
            "illustrative": 0.76,
            "black_grey_realism": 0.66,
            "dotwork": 0.60,
            "micro_realism": 0.54,
            "botanical": 0.28,
            "fine_line": 0.20,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.48,
            "density": 0.82,
            "contrast": 0.78,
            "realism": 0.82,
            "organic": 0.96,
            "geometric": 0.10,
            "symmetry": 0.12,
        },
        "motifs": [
            "caddisfly larva",
            "portable larval case",
            "pebbles",
            "bark fragments",
            "twigs",
            "aquatic insect",
            "natural camouflage",
            "entomology",
        ],
        "body_area": "lateral ribcage",
        "skin_tone": "medium-light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM113": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785859501/style_match/cards/SM113.jpg",
        "cloudinary_public_id": "style_match/cards/SM113",
        "primary_style": "cybersigilism",
        "style_weights": {
            "cybersigilism": 0.98,
            "geometric": 0.88,
            "abstract": 0.78,
            "blackwork": 0.58,
            "fine_line": 0.52,
            "minimalism": 0.40,
            "illustrative": 0.32,
            "engraving": 0.18,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.26,
            "density": 0.58,
            "contrast": 0.60,
            "realism": 0.16,
            "organic": 0.04,
            "geometric": 0.96,
            "symmetry": 0.18,
        },
        "motifs": [
            "mechanical metronome",
            "negative-space frame",
            "pendulum rod",
            "exposed gear",
            "fractured cyber-sigil",
            "glitch linework",
            "asymmetry",
            "rhythm",
        ],
        "body_area": "upper back beside spine",
        "skin_tone": "medium-dark",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM114": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785859508/style_match/cards/SM114.jpg",
        "cloudinary_public_id": "style_match/cards/SM114",
        "primary_style": "illustrative",
        "style_weights": {
            "illustrative": 0.98,
            "blackwork": 0.82,
            "black_grey_realism": 0.66,
            "neo_traditional": 0.52,
            "engraving": 0.48,
            "dotwork": 0.36,
            "ornamental": 0.30,
            "american_traditional": 0.22,
        },
        "visual_traits": {
            "color": 0.12,
            "line_weight": 0.64,
            "density": 0.78,
            "contrast": 0.86,
            "realism": 0.72,
            "organic": 0.74,
            "geometric": 0.30,
            "symmetry": 0.38,
        },
        "motifs": [
            "West African talking drum",
            "Anansi spider shadow",
            "drumstick",
            "rope tensioning",
            "impossible shadow",
            "folklore",
            "rhythm",
            "trickster",
        ],
        "body_area": "front shin",
        "skin_tone": "light",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM115": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785859516/style_match/cards/SM115.jpg",
        "cloudinary_public_id": "style_match/cards/SM115",
        "primary_style": "japanese",
        "style_weights": {
            "japanese": 0.98,
            "illustrative": 0.94,
            "engraving": 0.66,
            "black_grey_realism": 0.52,
            "neo_traditional": 0.48,
            "fine_line": 0.34,
            "blackwork": 0.30,
            "american_traditional": 0.18,
        },
        "visual_traits": {
            "color": 0.12,
            "line_weight": 0.48,
            "density": 0.72,
            "contrast": 0.60,
            "realism": 0.60,
            "organic": 0.66,
            "geometric": 0.20,
            "symmetry": 0.20,
        },
        "motifs": [
            "biwa-bokuboku",
            "tsukumogami",
            "anthropomorphic biwa",
            "self-plucking strings",
            "wooden limbs",
            "sandals",
            "instrument yokai",
            "Japanese folklore",
        ],
        "body_area": "outer forearm",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
}


def seed_sm111_sm115(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    for card_id, defaults in CARDS.items():
        TattooCard.objects.update_or_create(card_id=card_id, defaults=defaults)


def remove_sm111_sm115(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    TattooCard.objects.filter(card_id__in=CARDS).delete()


class Migration(migrations.Migration):
    dependencies = [("style_match", "0006_seed_sm106_sm110")]

    operations = [migrations.RunPython(seed_sm111_sm115, remove_sm111_sm115)]
