from django.db import migrations


CARDS = {
    "SM116": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785863159/style_match/cards/SM116.jpg",
        "cloudinary_public_id": "style_match/cards/SM116",
        "primary_style": "micro_realism",
        "style_weights": {
            "micro_realism": 0.98,
            "geometric": 0.88,
            "engraving": 0.74,
            "dotwork": 0.62,
            "black_grey_realism": 0.60,
            "fine_line": 0.48,
            "minimalism": 0.32,
            "illustrative": 0.20,
        },
        "visual_traits": {
            "color": 0.06,
            "line_weight": 0.18,
            "density": 0.58,
            "contrast": 0.52,
            "realism": 0.88,
            "organic": 0.08,
            "geometric": 0.94,
            "symmetry": 0.22,
        },
        "motifs": [
            "etched iron meteorite",
            "Widmanstätten pattern",
            "crystalline lattice",
            "meteorite slice",
            "nickel-iron",
            "crosshatched lamellae",
            "mineral specimen",
            "space rock",
        ],
        "body_area": "inner ankle",
        "skin_tone": "dark",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM117": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785863168/style_match/cards/SM117.jpg",
        "cloudinary_public_id": "style_match/cards/SM117",
        "primary_style": "watercolor",
        "style_weights": {
            "watercolor": 0.98,
            "abstract": 0.86,
            "minimalism": 0.66,
            "illustrative": 0.34,
            "color_realism": 0.22,
            "fine_line": 0.20,
            "geometric": 0.16,
            "dotwork": 0.05,
        },
        "visual_traits": {
            "color": 0.94,
            "line_weight": 0.12,
            "density": 0.44,
            "contrast": 0.46,
            "realism": 0.24,
            "organic": 0.74,
            "geometric": 0.42,
            "symmetry": 0.10,
        },
        "motifs": [
            "paper chromatography strip",
            "separated pigment bands",
            "binder clip",
            "chromatography paper",
            "capillary action",
            "four color bands",
            "laboratory experiment",
            "color separation",
        ],
        "body_area": "back of upper arm",
        "skin_tone": "medium-light",
        "quality_score": 0.96,
        "is_active": True,
        "is_approved": True,
    },
    "SM118": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785863176/style_match/cards/SM118.jpg",
        "cloudinary_public_id": "style_match/cards/SM118",
        "primary_style": "botanical",
        "style_weights": {
            "botanical": 0.98,
            "engraving": 0.92,
            "illustrative": 0.78,
            "fine_line": 0.62,
            "black_grey_realism": 0.54,
            "dotwork": 0.48,
            "color_realism": 0.24,
            "blackwork": 0.20,
        },
        "visual_traits": {
            "color": 0.18,
            "line_weight": 0.30,
            "density": 0.86,
            "contrast": 0.58,
            "realism": 0.88,
            "organic": 0.98,
            "geometric": 0.18,
            "symmetry": 0.32,
        },
        "motifs": [
            "thistle flower-head",
            "longitudinal cutaway",
            "florets",
            "seed chambers",
            "hollow stem",
            "botanical anatomy",
            "spines",
            "dissected plant specimen",
        ],
        "body_area": "inner calf",
        "skin_tone": "medium-dark",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
    "SM119": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785863184/style_match/cards/SM119.jpg",
        "cloudinary_public_id": "style_match/cards/SM119",
        "primary_style": "dotwork",
        "style_weights": {
            "dotwork": 0.98,
            "geometric": 0.94,
            "abstract": 0.72,
            "minimalism": 0.58,
            "ornamental": 0.42,
            "fine_line": 0.30,
            "blackwork": 0.24,
            "cybersigilism": 0.10,
        },
        "visual_traits": {
            "color": 0.0,
            "line_weight": 0.08,
            "density": 0.66,
            "contrast": 0.62,
            "realism": 0.03,
            "organic": 0.28,
            "geometric": 0.98,
            "symmetry": 0.96,
        },
        "motifs": [
            "Chladni nodal pattern",
            "vibrating square plate",
            "sand grains",
            "acoustic resonance",
            "standing waves",
            "nodal lines",
            "stippled field",
            "cymatic geometry",
        ],
        "body_area": "upper chest below collarbone",
        "skin_tone": "light",
        "quality_score": 0.97,
        "is_active": True,
        "is_approved": True,
    },
    "SM120": {
        "image_url": "https://res.cloudinary.com/dz0wuti9s/image/upload/v1785863197/style_match/cards/SM120.jpg",
        "cloudinary_public_id": "style_match/cards/SM120",
        "primary_style": "engraving",
        "style_weights": {
            "engraving": 0.97,
            "illustrative": 0.88,
            "black_grey_realism": 0.62,
            "fine_line": 0.56,
            "micro_realism": 0.48,
            "geometric": 0.38,
            "dotwork": 0.32,
            "minimalism": 0.12,
        },
        "visual_traits": {
            "color": 0.10,
            "line_weight": 0.32,
            "density": 0.78,
            "contrast": 0.54,
            "realism": 0.80,
            "organic": 0.30,
            "geometric": 0.74,
            "symmetry": 0.52,
        },
        "motifs": [
            "foot-powered pottery wheel",
            "unfinished clay vessel",
            "ridged pot",
            "kick wheel",
            "wooden frame",
            "flywheel",
            "pottery tool",
            "ceramics craft",
        ],
        "body_area": "inner forearm",
        "skin_tone": "medium",
        "quality_score": 0.98,
        "is_active": True,
        "is_approved": True,
    },
}


def seed_sm116_sm120(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    for card_id, defaults in CARDS.items():
        TattooCard.objects.update_or_create(card_id=card_id, defaults=defaults)


def remove_sm116_sm120(apps, schema_editor):
    TattooCard = apps.get_model("style_match", "TattooCard")
    TattooCard.objects.filter(card_id__in=CARDS).delete()


class Migration(migrations.Migration):
    dependencies = [("style_match", "0007_seed_sm111_sm115")]

    operations = [migrations.RunPython(seed_sm116_sm120, remove_sm116_sm120)]
