COPY = {
    "en": {
        "page_eyebrow": "Healing companion", "page_title": "Your healing, clearly tracked.",
        "artist_page_title": "Client healing, in one place.",
        "page_subtitle": "Keep photos, daily care and your artist conversation connected to this tattoo.",
        "updated": "Updated", "current_stage": "Current stage", "day": "Day",
        "tracking_window": "30-day tracking", "active": "Active", "healed": "Healed",
        "timeline_eyebrow": "Your path", "timeline_title": "Healing timeline",
        "today_eyebrow": "Today's care", "today_title": "Small care. Big outcome.",
        "mark_remaining": "Mark remaining as done", "routine_complete": "Today's routine is complete",
        "photo_eyebrow": "Visual record", "photo_title": "Photo check-in",
        "upload_photo": "Add today's photo", "save_photo": "Save check-in",
        "note_placeholder": "Optional note for you or your artist",
        "no_photos": "No check-in photos yet. Your first photo will start the visual timeline.",
        "first_photo": "First", "latest_photo": "Latest",
        "care_eyebrow": "Care guide", "care_title": "Follow your artist's instructions",
        "care_copy": "Tatzo keeps your routine and photos together. It does not diagnose healing or replace professional care.",
        "care_tip": "Keep the area clean, avoid picking, and use only the products and routine recommended for your tattoo.",
        "signals_eyebrow": "When to ask for help", "signals_title": "Do not wait when you are worried",
        "signals_one": "Message your artist if something looks or feels different from the instructions you received.",
        "signals_two": "Contact a healthcare professional if symptoms are worsening, spreading, or you feel unwell.",
        "stats_eyebrow": "At a glance", "stats_title": "Your healing activity",
        "current_day": "Current day", "days_remaining": "Days in tracking window",
        "checkins": "Photo check-ins", "routine_streak": "Care streak", "artist_responses": "Artist replies",
        "artist_eyebrow": "Your artist", "client_eyebrow": "Healing client",
        "artist_title": "Guided by the artist", "client_title": "Stay close to the client",
        "no_artist_message": "No healing-related message yet. Open the chat whenever you need it.",
        "message_artist": "Message your artist", "message_client": "Message the client",
        "achievements_eyebrow": "Your collection", "achievements_title": "Healing milestones",
        "first_checkin": "First check-in", "seven_day_streak": "7-day care streak",
        "three_checkins": "Three check-ins", "fully_healed": "Fully healed",
        "locked": "In progress", "unlocked": "Unlocked", "mark_healed": "Mark as healed",
        "empty_title": "Start tracking after a completed tattoo session",
        "empty_copy": "Completed tattoo appointments appear here so the client can start a private healing journal.",
        "start_tracker": "Start healing tracker",
        "no_appointments": "There are no completed tattoo sessions ready for tracking yet.",
        "journeys_title": "Healing journeys", "select_journey": "Choose a tattoo",
        "photo_saved": "Photo check-in saved.", "task_saved": "Care item updated.",
        "journey_started": "Healing tracker started.", "journey_healed": "Journey marked as healed.",
        "invalid_photo": "Please upload a JPG, PNG or WebP image up to 12 MB.",
        "chat_context": "Healing context",
        "chat_draft_client": "Hi! I would like to discuss the healing of “{title}”. It is currently day {day}.",
        "chat_draft_artist": "Hi! I am checking in about the healing of “{title}”. It is currently day {day}.",
        "task_wash": "Wash gently as instructed", "task_moisturize": "Apply the recommended thin layer",
        "task_sun": "Keep it away from direct sun", "task_friction": "Avoid scratching and friction",
        "phase_settling": "Peeling & settling",
    },
    "fr": {
        "page_eyebrow": "Compagnon de cicatrisation", "page_title": "Votre cicatrisation, suivie clairement.",
        "artist_page_title": "La cicatrisation des clients, au même endroit.",
        "page_subtitle": "Gardez les photos, les soins quotidiens et la conversation avec l'artiste liés à ce tatouage.",
        "updated": "Mis à jour", "current_stage": "Étape actuelle", "day": "Jour",
        "tracking_window": "Suivi sur 30 jours", "active": "Actif", "healed": "Cicatrisé",
        "timeline_eyebrow": "Votre parcours", "timeline_title": "Chronologie de cicatrisation",
        "today_eyebrow": "Soins du jour", "today_title": "Peu de gestes. Un grand résultat.",
        "mark_remaining": "Tout marquer comme fait", "routine_complete": "La routine du jour est terminée",
        "photo_eyebrow": "Suivi visuel", "photo_title": "Photo de suivi",
        "upload_photo": "Ajouter la photo du jour", "save_photo": "Enregistrer le suivi",
        "note_placeholder": "Note facultative pour vous ou votre artiste",
        "no_photos": "Aucune photo pour le moment. La première photo démarrera la chronologie visuelle.",
        "first_photo": "Première", "latest_photo": "Récente",
        "care_eyebrow": "Guide de soins", "care_title": "Suivez les consignes de votre artiste",
        "care_copy": "Tatzo regroupe votre routine et vos photos. Il ne pose pas de diagnostic et ne remplace pas un professionnel.",
        "care_tip": "Gardez la zone propre, ne grattez pas et utilisez uniquement la routine et les produits recommandés.",
        "signals_eyebrow": "Quand demander de l'aide", "signals_title": "N'attendez pas si quelque chose vous inquiète",
        "signals_one": "Écrivez à votre artiste si l'évolution diffère des consignes reçues.",
        "signals_two": "Contactez un professionnel de santé si les symptômes s'aggravent, s'étendent ou si vous vous sentez mal.",
        "stats_eyebrow": "En un coup d'œil", "stats_title": "Votre activité de cicatrisation",
        "current_day": "Jour actuel", "days_remaining": "Jours dans le suivi",
        "checkins": "Photos de suivi", "routine_streak": "Série de soins", "artist_responses": "Réponses de l'artiste",
        "artist_eyebrow": "Votre artiste", "client_eyebrow": "Client en cicatrisation",
        "artist_title": "Guidé par l'artiste", "client_title": "Restez proche du client",
        "no_artist_message": "Aucun message lié à la cicatrisation. Ouvrez la discussion quand nécessaire.",
        "message_artist": "Écrire à votre artiste", "message_client": "Écrire au client",
        "achievements_eyebrow": "Votre collection", "achievements_title": "Étapes de cicatrisation",
        "first_checkin": "Premier suivi", "seven_day_streak": "7 jours de soins",
        "three_checkins": "Trois suivis", "fully_healed": "Entièrement cicatrisé",
        "locked": "En cours", "unlocked": "Débloqué", "mark_healed": "Marquer comme cicatrisé",
        "empty_title": "Commencez le suivi après une séance terminée",
        "empty_copy": "Les rendez-vous tatouage terminés apparaissent ici pour créer un journal privé.",
        "start_tracker": "Démarrer le suivi", "no_appointments": "Aucune séance terminée n'est prête pour le suivi.",
        "journeys_title": "Parcours de cicatrisation", "select_journey": "Choisir un tatouage",
        "photo_saved": "Photo de suivi enregistrée.", "task_saved": "Soin mis à jour.",
        "journey_started": "Suivi de cicatrisation démarré.", "journey_healed": "Parcours marqué comme cicatrisé.",
        "invalid_photo": "Ajoutez une image JPG, PNG ou WebP de 12 Mo maximum.",
        "chat_context": "Contexte de cicatrisation",
        "chat_draft_client": "Bonjour ! Je souhaite parler de la cicatrisation de « {title} ». Nous sommes actuellement au jour {day}.",
        "chat_draft_artist": "Bonjour ! Je prends des nouvelles de la cicatrisation de « {title} ». Nous sommes actuellement au jour {day}.",
        "task_wash": "Nettoyer doucement selon les consignes", "task_moisturize": "Appliquer la fine couche recommandée",
        "task_sun": "Éviter le soleil direct", "task_friction": "Éviter de gratter et les frottements",
        "phase_settling": "Desquamation et stabilisation",
    },
    "ru": {
        "page_eyebrow": "Сопровождение заживления", "page_title": "Заживление — понятно и наглядно.",
        "artist_page_title": "Заживление клиентов — в одном месте.",
        "page_subtitle": "Фото, ежедневный уход и общение с мастером связаны с конкретной татуировкой.",
        "updated": "Обновлено", "current_stage": "Текущий этап", "day": "День",
        "tracking_window": "30 дней наблюдения", "active": "Активно", "healed": "Зажило",
        "timeline_eyebrow": "Ваш путь", "timeline_title": "Этапы заживления",
        "today_eyebrow": "Уход сегодня", "today_title": "Небольшой уход. Большой результат.",
        "mark_remaining": "Отметить оставшееся", "routine_complete": "Уход на сегодня выполнен",
        "photo_eyebrow": "Фотоистория", "photo_title": "Фото-чек-ин",
        "upload_photo": "Добавить сегодняшнее фото", "save_photo": "Сохранить чек-ин",
        "note_placeholder": "Необязательная заметка для себя или мастера",
        "no_photos": "Фото пока нет. Первый чек-ин запустит наглядную историю заживления.",
        "first_photo": "Первое", "latest_photo": "Последнее",
        "care_eyebrow": "Уход", "care_title": "Следуйте рекомендациям вашего мастера",
        "care_copy": "Tatzo хранит уход и фотографии вместе, но не ставит диагнозов и не заменяет специалиста.",
        "care_tip": "Содержите область в чистоте, не сдирайте корочки и используйте только рекомендованные средства и режим ухода.",
        "signals_eyebrow": "Когда обратиться за помощью", "signals_title": "Не ждите, если вас что-то тревожит",
        "signals_one": "Напишите мастеру, если заживление отличается от полученных рекомендаций.",
        "signals_two": "Обратитесь к врачу, если симптомы усиливаются, распространяются или ухудшается самочувствие.",
        "stats_eyebrow": "Коротко", "stats_title": "Активность заживления",
        "current_day": "Текущий день", "days_remaining": "Дней в наблюдении",
        "checkins": "Фото-чек-ины", "routine_streak": "Серия ухода", "artist_responses": "Ответы мастера",
        "artist_eyebrow": "Ваш мастер", "client_eyebrow": "Клиент на заживлении",
        "artist_title": "Поддержка мастера", "client_title": "Оставайтесь на связи с клиентом",
        "no_artist_message": "Сообщений о заживлении пока нет. Откройте чат, когда понадобится.",
        "message_artist": "Написать мастеру", "message_client": "Написать клиенту",
        "achievements_eyebrow": "Ваша коллекция", "achievements_title": "Этапы и достижения",
        "first_checkin": "Первый чек-ин", "seven_day_streak": "7 дней ухода",
        "three_checkins": "Три чек-ина", "fully_healed": "Полностью зажило",
        "locked": "В процессе", "unlocked": "Получено", "mark_healed": "Отметить как зажившее",
        "empty_title": "Начните наблюдение после завершённого сеанса",
        "empty_copy": "Завершённые тату-сеансы появятся здесь, чтобы клиент мог создать приватный журнал.",
        "start_tracker": "Начать отслеживание", "no_appointments": "Пока нет завершённых тату-сеансов для отслеживания.",
        "journeys_title": "Истории заживления", "select_journey": "Выберите татуировку",
        "photo_saved": "Фото-чек-ин сохранён.", "task_saved": "Пункт ухода обновлён.",
        "journey_started": "Отслеживание заживления запущено.", "journey_healed": "История отмечена как зажившая.",
        "invalid_photo": "Загрузите JPG, PNG или WebP размером до 12 МБ.",
        "chat_context": "Контекст заживления",
        "chat_draft_client": "Привет! Хочу обсудить заживление «{title}». Сейчас идёт день {day}.",
        "chat_draft_artist": "Привет! Хочу уточнить, как проходит заживление «{title}». Сейчас идёт день {day}.",
        "task_wash": "Аккуратно промыть по инструкции", "task_moisturize": "Нанести рекомендованный тонкий слой",
        "task_sun": "Избегать прямого солнца", "task_friction": "Не чесать и избегать трения",
        "phase_settling": "Шелушение и стабилизация",
    },
}

TIMELINE = {
    "en": {
        "1": {"phase": "Fresh tattoo", "heading": "Day 1 — protect and follow the wrap plan", "copy": "Keep the instructions from your artist close and handle the area gently.", "tags": ["Artist instructions", "Gentle care"]},
        "3": {"phase": "Early care", "heading": "Day 3 — keep the routine consistent", "copy": "Continue the cleaning routine you were given and avoid rubbing from clothing.", "tags": ["Keep clean", "Avoid friction"]},
        "7": {"phase": "Peeling & settling", "heading": "Day 7 — let the skin settle naturally", "copy": "Do not pick or scratch. Keep following the product and washing advice from your artist.", "tags": ["Do not pick", "Stay consistent"]},
        "14": {"phase": "Surface recovery", "heading": "Day 14 — continue protecting the tattoo", "copy": "Keep the area comfortable and protect it from direct sun while the deeper layers continue settling.", "tags": ["Sun protection", "Gentle moisture"]},
        "30": {"phase": "Long-term care", "heading": "Day 30 — move into long-term care", "copy": "Continue protecting the tattoo from UV exposure and keep your artist's long-term advice.", "tags": ["Long-term care", "UV protection"]},
        "healed": {"phase": "Tracking complete", "heading": "Marked as healed", "copy": "Your journal remains available with its photos, routine and artist conversation.", "tags": ["Journal saved", "Milestone"]},
    },
    "fr": {
        "1": {"phase": "Tatouage récent", "heading": "Jour 1 — protégez et suivez les consignes", "copy": "Gardez les instructions de votre artiste à portée de main et manipulez la zone avec douceur.", "tags": ["Consignes de l'artiste", "Soin doux"]},
        "3": {"phase": "Premiers soins", "heading": "Jour 3 — gardez une routine régulière", "copy": "Continuez le nettoyage conseillé et évitez les frottements des vêtements.", "tags": ["Garder propre", "Éviter les frottements"]},
        "7": {"phase": "Desquamation et stabilisation", "heading": "Jour 7 — laissez la peau évoluer naturellement", "copy": "Ne grattez pas et ne retirez rien. Continuez les produits et le lavage conseillés.", "tags": ["Ne pas gratter", "Rester régulier"]},
        "14": {"phase": "Récupération de surface", "heading": "Jour 14 — continuez à protéger le tatouage", "copy": "Gardez la zone confortable et protégez-la du soleil direct pendant la stabilisation.", "tags": ["Protection solaire", "Hydratation douce"]},
        "30": {"phase": "Soins à long terme", "heading": "Jour 30 — passez aux soins durables", "copy": "Continuez à protéger le tatouage des UV et suivez les conseils à long terme de votre artiste.", "tags": ["Soin durable", "Protection UV"]},
        "healed": {"phase": "Suivi terminé", "heading": "Marqué comme cicatrisé", "copy": "Votre journal reste disponible avec les photos, la routine et les échanges avec l'artiste.", "tags": ["Journal conservé", "Étape atteinte"]},
    },
    "ru": {
        "1": {"phase": "Свежая татуировка", "heading": "День 1 — защита и инструкции мастера", "copy": "Держите рекомендации мастера под рукой и обращайтесь с областью максимально аккуратно.", "tags": ["Инструкции мастера", "Бережный уход"]},
        "3": {"phase": "Начальный уход", "heading": "День 3 — сохраняйте регулярность", "copy": "Продолжайте рекомендованное очищение и избегайте трения одеждой.", "tags": ["Содержать в чистоте", "Избегать трения"]},
        "7": {"phase": "Шелушение и стабилизация", "heading": "День 7 — дайте коже восстановиться естественно", "copy": "Не расчёсывайте и не сдирайте кожу. Продолжайте уход по рекомендациям мастера.", "tags": ["Не сдирать", "Соблюдать уход"]},
        "14": {"phase": "Восстановление поверхности", "heading": "День 14 — продолжайте защищать татуировку", "copy": "Поддерживайте комфорт кожи и защищайте область от прямого солнца.", "tags": ["Защита от солнца", "Мягкое увлажнение"]},
        "30": {"phase": "Долгосрочный уход", "heading": "День 30 — переходите к постоянному уходу", "copy": "Продолжайте защищать татуировку от ультрафиолета и следуйте долгосрочным советам мастера.", "tags": ["Постоянный уход", "Защита от УФ"]},
        "healed": {"phase": "Наблюдение завершено", "heading": "Отмечено как зажившее", "copy": "Ваш журнал остаётся доступным вместе с фотографиями, уходом и перепиской с мастером.", "tags": ["Журнал сохранён", "Этап завершён"]},
    },
}


def get_copy(language_code):
    language = (language_code or "en").split("-")[0].lower()
    return COPY.get(language, COPY["en"]), TIMELINE.get(language, TIMELINE["en"]), language
